stonesoup/functions.py
stonesoup/tests/test_functions.py

Changed v@v.T to v.T@v since v is a row vector not a column vector. This was causing the merged covariance to be calculated incorrectly.

Fixed bug in gm_reduce_single

---

stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_ca.py

Fix the mistake of constant acceleration model. The third term is divided by 2, namely 'sp.power(time_interval_sec, 2) / 2' in 'Stone-Soup/stonesoup/models/transition/linear.py' and 'sp.power(timediff, 2) / 2' in 'Stone-Soup/stonesoup/models/transition/tests/test_ca.py'

fix-ConstantAcceleration transition model

---

stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_ou.py

Added an implementation of the Ornstein-Uhlenbeck transition model.
Similar to `ConstantVelocity`, `OrnsteinUhlenbeck` assumes that a target moves with constant velocity, but also includes a damping term that causes the velocity to exponentially decay to zero if there is no input for a prolonged period of time.

Add Ornstein-Uhlenbeck transition model

---

stonesoup/feeder/filter.py
stonesoup/feeder/tests/conftest.py
stonesoup/feeder/tests/test_filter.py

This pull request includes 2 new `DetectionFeeder` objects, which may be of interest:
1. The `MetadataValueFilter` class aims to provide a simple, yet relatively flexible scheme for filtering/removing unwanted detections based on the value of some metadata field (e.g. MMSI, SNR, size, etc.). Being a subclass of `MetadataReducer`, this feeder inherits the `metadata_field` property, which it uses to store the field name of the meta value of interest. For any given detection, assuming that the meta field exists, the feeder passes the extracted meta value `x` through a user-defined unary operator/function of the form `b=f(x)`, whose handle is stored in the `operator` class property, and must be configured to return `True` if the detection should be allowed through the filter (i.e. yielded) …

Detection Feeders

---

stonesoup/functions.py
stonesoup/types/array.py
stonesoup/types/tests/test_array.py
stonesoup/types/tests/test_state.py

This creates a proper Matrix base class which inherits from Numpy's ndarray, StateVector, and Covariance Matrix are now subtypes of this Matrix class.  The output from mixed operations such as CovarianceMatrix*ndarray returns a StoneSoup type. This is most likely the desired behaviour, and allows the code to handle matrix operations involving Bearing or Elevation types properly.
Also added convenience functions for the creation a StateVector. StateVector returns a Nx1 matrix, so if the passed in data can be easily converted to this, then the conversion is done. For example
StateVector([1, 2, 3]) = StateVector([[1, 2, 3]] = StateVector([[1], [2], [3]]). These statements all create the same 3x1 StateVector.

Update StateVector and Array classes. Add convenience handling for StateVector

---

README.md

This commit aims to fix an error in the README file. In the section about "Dependencies" the protocol in the link to the utm library was defined twice. It is a minor bug, but it may lead to inconvenience for users trying to explore if the stonesoup project is a good option for them.

Fix double "https://" in README link to utm Lib

---

stonesoup/types/state.py
stonesoup/types/track.py

Following discussions with @sdhiscocks during Fusion in relation to #118, this pull request aims to solve the performance issues relating to reading metadata as follows:
- Track objects will now maintain a copy of what should be the most up-to-date metadata at each time. Thus, reading metadata should be more efficient, at the expense of the additional memory required to store the metadata and a small computational overhead when new states are added to a track.
- Metadata is updated automatically every time a new state is added to a track. This assumes (as we have done so far) that the last state in the list of states is also the latest one, i.e. the proposed approach will "fail" if states are added in an out-of-sequence manner.
- Although not implemented here, this approach can be …

Track metadata handling update

---

stonesoup/models/base.py
stonesoup/models/control/linear.py
stonesoup/models/measurement/base.py
stonesoup/models/measurement/linear.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_lg.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/models/transition/base.py
stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_ca.py
stonesoup/models/transition/tests/test_combined.py
stonesoup/models/transition/tests/test_ct.py
stonesoup/models/transition/tests/test_cv.py
stonesoup/models/transition/tests/test_ou.py
stonesoup/models/transition/tests/test_rw.py
stonesoup/models/transition/tests/test_singer.py
stonesoup/models/transition/tests/test_singer_approximate.py
stonesoup/models/transition/tests/test_time_invariant.py

This removes repeated code and standardises use of probability distribution, which could be more easily be extend for different probability distributions in future.
The pdf method now also returns _Probability_ type.

Move all rvs and pdf methods to GaussianModel class

---

stonesoup/simulator/simple.py
stonesoup/simulator/tests/conftest.py
stonesoup/simulator/tests/test_detections.py
stonesoup/simulator/tests/test_groundtruth.py
stonesoup/types/groundtruth.py
stonesoup/writer/tests/test_yaml.py

The ground truth simulators take a list of transition models, they
then switch between these based on a Markov transition matrix that the
user inputs.
The detection simulator changes the probability of detection
based on what transition model the ground truth user is using at the
given time.

Adds a variety of switching simulators.

---

stonesoup/functions.py
stonesoup/tests/test_functions.py

This allows for example changes in large values, where single delta of `1E-8` may be less that distance to the next floating point number, and such delta was effectively zero.

Add multi-dimension delta to Jacobian function

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

This changes the `SinglePointInitiator` to use a Extended Kalman Updater, rather than the non-linear Kalman Filter. As the KF/EKF updater only differs on how the measurement matrix is fetch, this results in no change to the linear usage, but adds support to non-linear case.

Modify SinglePointInitiator to work with non-linear models

---

stonesoup/hypothesiser/distance.py
stonesoup/hypothesiser/probability.py

These aren't really required, as no comparison to measurement space is done. This also causes issues where no measurement model is provided for an updater, as reasonable use case when adding measurement models to detections.

Avoid calculating measurement prediction for missed detections

---

stonesoup/base.py
stonesoup/tests/test_declarative.py

This branch adds getter and setter options to Stone Soup `Property`s, analogous to those for Python `property`s. 
It also added the ability to make a `Property` read only, such that it is written once (in the parent object's constructor) and thereafter cannot be changed. 
Tests are also added to `test_declarative.py`

Property extensions

---

docs/source/stonesoup.feeder.rst
stonesoup/feeder/multi.py
stonesoup/feeder/tests/test_multi.py

This enables multiple detectors to feed into single tracker, e.g. for a multi-sensor tracking scenario.

Add Multi-detector Feeder class

---

stonesoup/sensor/radar/tests/test_radar.py

Fix to the randomly failing Swerling test. It is a random test, and would fail about 1 in 50 times or so.
This commit just loosens the tolerances, and it has now 10000 times without failing.

Loosen tolerances on Swerling tests, to reduce chance of random failure

---

stonesoup/dataassociator/_assignment.py

This PR introduces a speed up to GNNWith2DAssignment. This is achieved by reducing the number of calls to ``numpy.unravel_index()``, which seemed to be adding a significant overhead.
To test the achieved performance, a simulation is run that involves 5000 targets over 1 hour, with 250 detections per second.
This is a view of the profiler output prior to the change:
And this is a view of the profiler output using the change in this PR:
The overall simulation runtime was reduced from ```2:42:21``` to ```1:51:37``` (```h:mm:ss```).

Speed up GNNWith2DAssignment

---

stonesoup/smoother/lineargaussian.py
stonesoup/smoother/tests/test_lineargaussian.py

This exploits the fact that hypotheses are stored on updates to fetch predictions from tracks, saving need to maintain these via another method.

Enable smoother to extract estimates from track

---

stonesoup/serialise.py
stonesoup/tests/test_serialise.py

Previously this would raise and error as it didn't know how to represent them.

Add support for numpy int and float types to serialise

---

stonesoup/sensor/radar/radar.py

The AESA radar `measure` function was previously written so that saved a reference to a measurement model with each detection that is later mutated. This code change it to use a deepcopy instead.

Update AESARadar to avoid mutating measurement model

---

stonesoup/functions.py
stonesoup/tests/test_functions.py

Also included tests which demonstrate this. Note that the state vectors of sigma points will remain as integers when input is integers (is this the behaviour we want?)
Fixes #195

Fix gauss2sigma raising error when state vector has integers

---

docs/source/stonesoup.initiator.rst
stonesoup/initiator/tests/test_wrapper.py
stonesoup/initiator/wrapper.py
stonesoup/serialise.py
stonesoup/tests/test_serialise.py
stonesoup/types/track.py

By default Stone Soup stores the track history for all tracks in memory.  If
running Stone Soup on very large data your application may run out of memory
and the process terminated - often by the operating system.
This wrapper converts the states space list to a collections.deque data
type with the maximum length specified.

Added StatesLengthLimiter

---

docs/source/conf.py

This resolves issues with building documentation.

Add reader video dependencies to mock imports for documentation

---

stonesoup/sensor/base.py
stonesoup/sensor/tests/test_sensor.py

A little, and obscure, mistake in setting the orientation of a platform with an internal sensor. Embarrassingly, there was a matching typo in the test...
A very small fix, but important.

Fix orientation setter in sensors with internal platforms.

---

stonesoup/dataassociator/probability.py
stonesoup/resampler/particle.py

This PR supersedes #152. The following changes have been applied:
- The branch has been rebased to the latest ``master`` commit.
- An ``attrgetter`` is now used when sorting the weights in ``SystematicResampler``
- Minor formatting has been applied to ``JPDA``.

JPDA and SystematicResampler Fixes (updated)

---

stonesoup/feeder/geo.py
stonesoup/feeder/tests/test_geo.py
stonesoup/functions.py
stonesoup/initiator/tests/test_simple.py
stonesoup/models/measurement/nonlinear.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/tests/test_passive.py
stonesoup/simulator/tests/test_platform.py
stonesoup/types/array.py
stonesoup/types/tests/test_array.py

This pull request updates StateVector indexing and code that uses it to demonstrate the change suggested in issue #186. I think this is a simple and useful update, but if people feel this over-complicates the Statevector class for little benefit, then the PR can be shelved.

Change StateVector indexing 

---

setup.py
stonesoup/functions.py
stonesoup/models/base.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/tests/test_functions.py
stonesoup/tracker/simple.py
stonesoup/types/angle.py
stonesoup/types/array.py
stonesoup/types/particle.py
stonesoup/types/state.py
stonesoup/types/tests/test_angle.py
stonesoup/types/tests/test_state.py
stonesoup/updater/tests/test_particle.py

This includes a number of changes to how `Matrix` type is implemented which will allow greater customisation if required. In particular, a new `StateVectors` type has been created which handles the case where calculations of averages (and in turn covariance) were incorrect when using `Angle` types.
`Angle` types now include a average method, which returns a circular mean. This removes an issue when calculating means near the point of angle wrapping.
These changes were primarily done for bug identified when calculating mean of particles, and such some minor changes to `Particle` and `Particle` type have been made.
Some functions have also been updated, as these are a set of state vectors, so can take advantage of the new type. This includes updating the Mixture Tracker
The array changes …

Add StateVectors type and modify array handling

---

stonesoup/metricgenerator/base.py
stonesoup/metricgenerator/metrictables.py
stonesoup/metricgenerator/tests/test_tables.py

Adds a new kind of metric visualisation, so far implemented for SIAP metrics only. This allows metrics to be displayed along with a short description of what the metric means as well as a target value for each metric (as these can vary). The metric value is also shown with a coloured background from red-green to visually represent the accuracy of each metric.
This will be of particular interest to the OSTEWG challenge participants, as it provides an easy way of comparing the accuracy of different trackers.

SIAP metric output table with red and green visual

---

docs/source/stonesoup.gater.rst
docs/source/stonesoup.rst
stonesoup/dataassociator/probability.py
stonesoup/dataassociator/tests/test_probability.py
stonesoup/gater/__init__.py
stonesoup/gater/base.py
stonesoup/gater/distance.py
stonesoup/gater/filtered.py
stonesoup/gater/tests/conftest.py
stonesoup/gater/tests/test_distance.py
stonesoup/gater/tests/test_filtered.py

Summary
----------
This PR adds a `Gater` base class which can be used to wrap hypothesisers, therefore allowing for the reduction (a.k.a gating) of the hypotheses before they are processed by data association.
Contributions
---------------
The main contributions/changes are outlined below:
- The concept of a `Gater` object has been introduced. `Gaters` wrap `Hypothesisers` in a similar way to how `Feeders` wrap `Detectors`. As such, the `Gater` class is defined as a sub-class of `Hypothesiser`. This idea has also been previously discussed [here](https://github.com/dstl/Stone-Soup/pull/145#issuecomment-555832268), albeit in a slightly different context.
- The `FilteredDetectionsHypothesiser` has now been renamed to `FilteredDetectionsGater` as it falls under the `Gater` class …

Add Gater classes

---

stonesoup/types/angle.py

Use of `Probability.sum()` can cause issues with negative weights, and also is different sum method in default `numpy.average` method used for non-Angle types in the state vector (so chance sum could be different when near zero weights present).

Modify Angle type average to use numpy.sum()

---

stonesoup/types/array.py

This resolves an issue where average would fail when passing custom
types in state vectors.

Fix StateVectors average method with custom types

---

stonesoup/types/array.py
stonesoup/types/tests/test_array.py

This means that a StateVector of an invalid shape can't be returned e.g. `(n, )`, where subsequent calls of `invalid_state_vector[n]` would raise error as this would attempt `invalid_state_vector[n, 0]`.

Cast array type of StateVector when slicing

---

docs/source/stonesoup.platform.rst
stonesoup/platform/base.py
stonesoup/platform/tests/test_platform_base.py
stonesoup/platform/tests/test_platform_simple.py
stonesoup/sensor/sensor.py
stonesoup/sensor/tests/test_sensor.py
stonesoup/simulator/simple.py
stonesoup/simulator/tests/test_platform.py

This merge changes the state property within the Platform object to be a StateMutableSequence rather than an individual State. All original behaviours remain the same however Platforms now maintain history of States. 
This has application in simulations, plotting and metric assessment (when using platforms rather than ground truth simulations). A Dummy simulation class has also been added which returns an empty set, this can be used in conjunction with the PlatformDetectionSimulator to produce simulations with only defined platform objects.

Platform state mutable

---

stonesoup/serialise.py

When not using deep construct, some mutable types may not be populated e.g. model lists. This change forces deep construct when creating components.

Fix issue with YAML requiring deep construct

---

stonesoup/initiator/simple.py
stonesoup/models/base.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py

This model takes 2D positional cartesian coordinates and outputs bearing-only measurements.
Appropriate modifications to base class and measurement initiator were made to accommodate a 1D output.

Add bearing-only measurement model

---

docs/source/conf.py
docs/source/doc_extensions.py
setup.py

Apply upstream changes to _matplotlib_ scraper to enable animation support.
Longer term would be good to work with Sphinx-Gallery project so we don't need this custom scraper.

Fix Sphinx-Gallery scraper animations

---

.circleci/config.yml

This should show coverage of sphinx-gallery examples
Includes addition of flags to enable see which lines were executed under which tests.

Add coverage and codecov upload to documentation build

---

stonesoup/types/array.py
stonesoup/types/tests/test_array.py

This PR fixes the indexing issues reported in #268

Override StateVector.flatten() and StateVector.ravel() functions

---

stonesoup/base.py
stonesoup/platform/base.py
stonesoup/sensor/tests/test_sensor.py

This commit makes two changes to address the issues raised by @gawebb-dstl in #262 :
1. Modify the `sensors` Property of a `Platform` to make it read-only (including making it effectively immutable)
2. Add a `__deepcopy__` method to the `Base` class to allow deep copying of a platform. This needs some thought as it may have unintended consequences. I can't see that it will, but I'd appreciate more eye on this. 
Thanks to @sdhiscocks for the idea of a getter returning a tuple and @gawebb-dstl for the test scenarios!

Fix issues with copying platforms

---

stonesoup/functions.py
stonesoup/tests/test_functions.py

This PR aims to fix the issue reported in #277

Fix rounding error issues for int-based state vectors in gauss2sigma

---

stonesoup/predictor/_utils.py
stonesoup/predictor/kalman.py
stonesoup/predictor/particle.py
stonesoup/predictor/tests/test_kalman.py

When passing a `StateMutableSequence` (e.g. a track) to a predictor using caching, the cache can incorrectly return results if same track and time stamp are passed in multiple times. This can be the case with multi-sensor example, where an update has occurred from one sensor, then a detection from another sensor is processed at the same time stamp.
This fixes the issue by using a custom lru_cache decorator that extracts the current state if input is mutable sequence.

Fix caching issue with states/mutable-sequences with predictor

---

stonesoup/models/measurement/tests/test_models.py
stonesoup/sensor/radar/tests/test_radar.py
stonesoup/sensor/tests/test_sensor.py

Issue in tests was caused by have state vector which was just lists of lists, rather than `StateVector` or `numpy.ndarray` (warning currently, but future will raise error). Also catch expected warnings raised when reassigning sensors to another platform.

Fix warnings raised for NumPy NEP34 and sensor reassignment

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

Fixed the covariance calculation in the SimpleMeasurementInitiator.  A diag_load parameter was added to the initiator (default =0) which adds a diagonal load value to the resulting covariance matrix. This was due to the Cholesky factorization complaining that the matrix was not positive definite.
The test code was also updated and corrected to test the returned covariance matrix i.e. some additional assert are tested.
I tested this with the UAV tutorial and the Sensor_Platform_Simulation example, which were having problems using the SimpleMeasurementInitiator. They both work now, however the Sensor_Platform_Simulation requires a small diag_load value to be supplied i.e. 1e-16.

Fix initiator covariance issue.

---

stonesoup/reader/yaml.py
stonesoup/serialise.py
stonesoup/tests/test_serialise.py
stonesoup/writer/tests/test_yaml.py

- Add support for Array, Angle and Numeric types in YAML serialiser
- Allow setting of YAML parser type, so faster C library can be used for parsing

Add support for array/number types and parser type in YAML

---

stonesoup/platform/base.py
stonesoup/platform/tests/test_platform_base.py
stonesoup/platform/tests/test_platform_simple.py

Returning a length 2 vector sometimes led to casting errors with platform orientations and sensor rotation offsets.
Note: May be worth allowing an input of length 1 (user inputs single bearing for 2D sensor rotation offset)

Change 2D sensor/platform orientations to 3D shape

---

stonesoup/metricgenerator/ospametric.py
stonesoup/metricgenerator/tests/test_ospametric.py

For OSPA, cost matrix should be square, with `c` value for mismatched number of tracks and truths.
This also fixes a bug where when number of tracks or truths is 1, that the index of association would be set to 1, rather than 0 (assume this is simple off-by-one error by original author).
Also includes general code tidy and some documentation fixes.

Fix (G)OSPA Metrics

---

stonesoup/sensor/radar/radar.py

The dwell centre needed to be kept within (-180, 180) degrees.
Note:
Have also cleaned-up imports

Fix rotating radar dwell centre calculation

---

stonesoup/reader/file.py

This fix removes the dangling file handlers the were created on initialization inside the Reader classes. This generally wasn't an issue until to you changed git branches and git tried to modify the csv file that had an open file handle. I've left in the custom initialization for the Text and Binary subclasses because we will likely add something at some point.
Resolves #254.

Fix leftover open file handles.

---

docs/source/stonesoup.models.transition.rst
stonesoup/models/transition/base.py
stonesoup/models/transition/linear.py
stonesoup/models/transition/nonlinear.py
stonesoup/models/transition/tests/test_combined.py

To accommodate combinations of transition models that do not have matrix representations (or other non-linear aspects), a new combined model was needed.
This also adds a new base class for combined models to inherit from.
Notes:
-Test is currently a copy of the linear equivalent. This should be altered when non-linear transition models are added to Stone Soup.

Add CombinedNonlinearGaussianTransitionModel

---

stonesoup/platform/tests/test_platform_simple.py
stonesoup/sensor/radar/__init__.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py

Modification to change the sensor names to match that of the measurement models they use, this reduces potential for confusion when configuring sensors. 
For example: `class RadarRangeElevationBearing(RadarRangeBearing)` becomes `class RadarElevationBearingRange(RadarBearingRange)`  and matches `CartesianToElevationBearingRange` measurement method.
Suggested that this is not merged until after tutorials are finished

Sensor-Measurement model consistency change

---

docs/demos/Smooth_Platform_Coordinate_Transitions.py
stonesoup/simulator/transition.py

Avoids the need for the `new_model` approach in transition models. 
Note this is a PR onto #289 , not a pull to `master`. I suggest that this PR is either pulled onto #289 before merge, or that #289 is updated to include this commit, then this PR is closed.

Refactor to avoid nested models

---

stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py
stonesoup/sensor/tests/test_passive.py
stonesoup/simulator/platform.py
stonesoup/simulator/tests/conftest.py
stonesoup/simulator/tests/test_platform.py

Changes to sensor tests to account for ground truths being passed-in, and measurements being received, as sets.
As well as a bit of adjustment in state definitions in test files to account for larger character limit.

Modify sensors to measure sets of ground truth states

---

stonesoup/base.py

Error previously used the wrong property name (taken from previous loop)
[ci skip]

Correct property name in specification error

---

stonesoup/base.py
stonesoup/tests/test_declarative.py

This issue was caused by removed properties in a new classes parent(s), being added into the new class by using properties from further ancestors. This change ensures that only properties of direct parents are used.
New test added which demonstrated this, as prior to fix, `_TestSubSubclassRemoveProperty` would fail to initialise, as it would expect `property_a` to be provided on initialisation, despite being fixed value in parent.
Also tidied up handling of properties, as there was multiple loops, assignments, etc. that weren't needed or could be consolidated.

Fix issue with properties being reinstated from ancestors

---

stonesoup/sensor/radar/tests/test_radar.py

Sometimes the addition of noise to the last measurement call led to a target being out of the fov of the radar.

Fix rotating radar test

---

stonesoup/base.py
stonesoup/platform/base.py
stonesoup/tests/test_declarative.py

The recent change to Properties exposed flaws in some of my code (I was previously abusing the old incorrect behaviour).
In fixing the problem, the solution turned out to be to make Properties more like Python `property`s, in [how getters, setters and deleters are handled](https://docs.python.org/3/howto/descriptor.html#properties). 
Hat tip to @sdhiscocks for the approach, which is much neater and allows them to work much better (and behave nicely in subclasses too).

Change Property getters and setters 

---

stonesoup/metricgenerator/tracktotruthmetrics.py

When there are no tracks or truths, there is no ambiguity as to track association. Therefore the target score of 1 makes more sense to return than the 'worst-case' of 0. [ci skip]

Change 'Ambiguity' metric to return 1 when there are no tracks/truths

---

stonesoup/platform/base.py
stonesoup/platform/tests/test_platform_base.py

Previously, by calling super's 'move' method, a new state was appended to the platform's states list after each loop of the interior while loop. Whereas, a state need only be appended after a full transition has been carried out.
Tests (which would fail on previous code) have been added to demonstrate this.

Modify MultiTransitionMovingPlatform to append state only after full transition

---

stonesoup/simulator/transition.py

I don't fully understand why this is needed, but it prevents some bugs when rerunning a platform simulation.
Since the model maker is only called once per platform, having a deepcopy shouldn't slow things down much.
[ci skip]

Modify custom models to take state deep-copies

---

stonesoup/serialise.py
stonesoup/tests/test_serialise.py

Was incorrectly passing first argument as `self`
Also added tests for dump/load, dump_all/load_all methods.

Fix YAML dump_all method

---

stonesoup/types/state.py
stonesoup/types/tests/test_state.py

This change allows a WeightedGaussianState to be created from a GaussianState, rather than specifying, state, cover and timestamp individually. It throws an exception if you over specify i.e. give it a state and a GaussianState. 
There are a couple ways of doing this - I choose not to have the gaussian_state as a Property, because this could lead to an inconsistency in the Timestamps. Note - changes to the state_vector or covar would be linked i.e. changing one would change the other. 
Please check the generated documentation to see if the appropriate.
Note - I also fixed an issue in the unit test. It wasn't properly testing the weight Property.

Add GaussianState initialization to WeightedGaussianState.

---

stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py
stonesoup/sensor/tests/test_passive.py

Allows for reference to the ground truth paths that produced the detections from the sensor.
Changes made in response to issue #196 
Note: Contains some format changes, import reordering in modified files.

Modify sensors to return sets of TrueDetection types

---

stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py

Previously, calling `measure` on an empty set would raise a StopIteration error as the method calculates a timestamp from the first truth in the set of truths passed in.

Fix rotating radar to handle measuring empty sets

---

stonesoup/initiator/simple.py
stonesoup/types/prediction.py
stonesoup/types/state.py
stonesoup/types/tests/test_prediction.py
stonesoup/types/tests/test_state.py
stonesoup/types/tests/test_update.py
stonesoup/types/update.py

This fixes the issue per title and some underlying causes relating to a `StateMutableSequence` type check being too specific.

Fix Prediction/Update from_state being called with StateMutableSequence

---

stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tracktotruthmetrics.py

Previously, having multiple states in a ground truth path with the same timestamp would lead the the _nu_j method entering an infinite loop.

Fix SIAP metric component _nu_j

---

stonesoup/models/base.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_combined.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/models/transition/tests/test_time_invariant.py

Rather than attempting to handle covariance arguments being None on instantiation, since some models have their own covariance methods, it seemed more appropriate to simply raise an error when rvs and pdf methods are called.
Closes #343 
Note: Only models with unmodified covariance methods are affected/tested

Modify gaussian models to raise errors with None covariances

---

setup.py
stonesoup/__init__.py

Version of Stone Soup is now dynamically fetch, which resolves issue when installing via pip install in non-editable mode from local directory.

Fix issue with version, effecting pip install with Read The Docs

---

docs/examples/Metrics.py
stonesoup/metricgenerator/manager.py
stonesoup/metricgenerator/tests/test_basicmetrics.py
stonesoup/metricgenerator/tests/test_manager.py
stonesoup/metricgenerator/tests/test_ospametric.py

This removes the need for multiple instance checks. The method will no longer throw an error with incorrect type inputs. This fixes the issue with a previously incorrect TypeError (#339).

Modify metric manager add_data method to have separate kwargs

---

stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/types/tests/test_track.py
stonesoup/types/track.py

Storing a track's metadata history will allow for metadata comparisons in metric generation.
Previously, calling `track.metadata` would return the track's metadata value at the end of its life.

Modify tracks to store metadata history

---

stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tracktotruthmetrics.py

Previously, ID SIAP calculations were done by considering `track.metadata` which calls on the metadata value of the track at the end of its life. This value may not reflect the value of the track at a particular timestamp in its lifetime. These changes introduce a new method which will index the track at the required timestamp, attain the relevant metadata, and make ID SIAP calculations using this (along with tests).

Modify ID SIAPs to consider track metadata at timestamps

---

stonesoup/sensor/radar/beam_pattern.py
stonesoup/sensor/radar/beam_shape.py
stonesoup/sensor/radar/tests/test_beam_pattern.py
stonesoup/sensor/radar/tests/test_beam_shape.py

Abstract method decorators were missing, mean erroneous use of classes not caught on initialisation.

Add abstractmethod decorator to Radar Beam Pattern/Shape

---

docs/source/doc_extensions.py

This avoids warnings being printed in docs, as well as reducing memory required (not that I think this is issue with figures in this case).

Close figures when finished processing file in Sphinx Gallery

---

stonesoup/sensor/radar/beam_pattern.py
stonesoup/sensor/radar/beam_shape.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_beam_shape.py
stonesoup/sensor/radar/tests/test_radar.py

- Fixes for some default arguments with radar sensors
- Change Radar `BeamShape` so `beam_width` is argument to `beam_power` method
- Add class constant for full width half maximum for `Beam2DGaussian`

AESA Radar and Beam Shape beam power method argument changes

---

stonesoup/dataassociator/base.py
stonesoup/dataassociator/neighbour.py
stonesoup/dataassociator/probability.py
stonesoup/hypothesiser/base.py
stonesoup/tracker/tests/conftest.py

* Move `DataAssociator` base class methods to `GlobalNearestNeighbour`
* These methods are only used for GNN, and don't seem relevant to other
data associators, as they use brute force unoptimised approach (which in
part is what having the GNN is there to demonstrate).
* Rename `time` to `timestamp` on `DataAssociator.associate()` methods
* This matches what was originally on the base class, more consistent with
use of `timestamp` elsewhere, and avoids using `time` name which is
standard library module.

Data Associator Class modifications

---

docs/source/_static/css/custom.css

Originally suggested in https://github.com/dstl/Stone-Soup/pull/249#issuecomment-649062509
Can be seen on the *Multi-Sensor Moving Platform Simulation Example*.

Fix animation control layout in Sphinx-Gallery examples

---

stonesoup/predictor/kalman.py
stonesoup/predictor/particle.py
stonesoup/predictor/tests/test_kalman.py
stonesoup/types/prediction.py

This would be useful for analysis (e.g. in post-processing, like deriving metrics) and in smoothing. A smoother requires knowledge the transition model used to make predictions. This could be defined externally, but it seems more efficient to reach into the prediction to find it, particularly as the transition model may change as the track is created.
I've made it optional (`default=None`) in `Prediction` but modified the current set of predictors to include the link to the transition model (via the `predict()` method). Should this latter instead be optional?

Adding link to TransitionModel in the Prediction

---

.github/CODEOWNERS
.github/workflows/docs-link.yml

This adds a [`CODEOWNERS` file](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) to enable auto assignment of reviewers.
This also adds a GitHub action to automatically add a link to docs built on CircleCI for pull request status checks (not sure this will work on this PR, as needs to be merged into _master_ first).

Add GitHub related files for reviewers and actions

---

docs/source/stonesoup.plugins.rst
docs/source/stonesoup.rst
stonesoup/plugins.py

Add ability to load plugins using package metadata in package's setup.py [entry_points](https://packaging.python.org/guides/creating-and-discovering-plugins/#using-package-metadata). This will enable third party Stone Soup components to be easily discoverable.

Add support for plugins

---

docs/examples/Metrics.py
stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tracktotruthmetrics.py

Time-based SIAP titles were previously not descriptive.
This change also prevents the time-based metrics from being picked-up in a print statement in the Examples doc, where previously long strings were output.
Tests altered accordingly.

Change time-based SIAP titles

---

stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/resampler/particle.py
stonesoup/updater/tests/test_pointprocess.py

- Remove print statements in tests
- Use `approx` comparison in measurement model tests with particles
- Ignore divide by zero warnings in `SystematicResampler`, and avoid underflow

Various test fixes for print statements, floating point errors and divide by zero warnings

---

stonesoup/types/state.py
stonesoup/types/tests/test_state.py

This PR tweaks error handling in `StateMutableSequence`
Before this change, any class that inherited from `StateMutableSequence` (e.g. `Platform` would give the following behaviour:
```python
platform = Platform(some_parameters)
platform.missing_attribute
```
```
AttributeError: 'State' object has no attribute 'missing_attribute'
```
This is odd behaviour, as `Platform` is not a `State` and caused me to spend an annoying amount of time debugging the problem.
After the PR, the error message would be:
```
AttributeError: 'Platform' object has no attribute 'missing_attribute'
```
This is much more helpful and seems like a sensible change at the expense of only a little more code.

Update StateMutableSequence error handling

---

stonesoup/types/state.py
stonesoup/types/tests/test_state.py

Following on from #386: In that PR I said that I hadn't quite fixed the problem, as custom error messages were still being swallowed 
This PR fixes that by using `__getattribute__` instead of `__getattr__`, which allows capture of the original error.
The test is also extended so that it fails before this PR, but passes after.

Prevent StateMutableSequence  from swallowing custom errors

---

docs/demos/UAV_tutorial.py
docs/examples/Sensor_Platform_Simulation.py
docs/tutorials/09_Initiators_&_Deleters.py
stonesoup/initiator/base.py
stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py
stonesoup/initiator/tests/test_wrapper.py
stonesoup/tracker/simple.py
stonesoup/tracker/tests/conftest.py

- Add timestamp to `Initiator.initiate()` method: This enables initiators to possibly take action when a timestamp occurs when no measurement is present.
- Allow `MultiMeasurementInitiator` to predict tracks: This allows cases where you may want to yield tracks that have survived
the deleter a number of time steps as well.

Include timestamp with Initiator and allow predictions with multi measurement initiator

---

docs/source/stonesoup.rst
stonesoup/platform/base.py
stonesoup/sensor/base.py
stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py

- Base `Platform` class `is_moving` should be a `property`.
- Document `measure()` method on sensor base class. Subclasses all have very similar docstrings, so removed those so they'll inherit parent.

Sensor and platform minor documentation changes

---

docs/demos/AIS_Solent_Tracker.py
docs/tutorials/09_Initiators_&_Deleters.py
docs/tutorials/10_Simulation_&_Tracking_Components.py
stonesoup/deleter/base.py
stonesoup/deleter/tests/test_base.py
stonesoup/deleter/tests/test_error.py
stonesoup/deleter/tests/test_multi.py
stonesoup/deleter/tests/test_time.py

Introduces option to deleters to remove the last state in a track that has caused it to be marked for deletion. State will only be removed if it is not an `update`. This is useful when there are large time steps between each incoming detection to a tracker.

Add option to delete posterior predictions from deleted tracks

---

stonesoup/deleter/error.py
stonesoup/deleter/tests/test_error.py

Sometimes it is useful to consider deleting a track only when particular components of its state vector become very uncertain. This change introduces a mapping to the `CovarianceBasedDeleter`, which allows the user to define which components of the track state should be taken in to consideration when evaluating a covariance trace.
For example, with a track state vector (x, vx, y, vy), the user might only want to delete a track if its positional uncertainties grow too large, in which case a mapping of [0, 2] could be passed in, in which case the deleter will sum the variance in x and y only.

Add mapping to CovarianceBasedDeleter

---

stonesoup/functions/__init__.py
stonesoup/functions/tests/test_functions.py

Updated gm_reduce_single to handle `means` passed in as `np.array` type. The `StateVectors` class overrides the average() routine to work properly. This causes an issue when a np.array type is passed into `gm_reduce_single`. Rather than force the user to pass in a StateVectors type, the easiest fix is to cast `means` as a StateVectors type.

Fix gm_reduce_single.

---

stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_combined.py

This is required to ensure that when using measurement based initiators, that the mapping is applied properly.

Add mapping to Combined Measurement Model

---

stonesoup/plotter.py

This speeds up plotting lots of measurements and clutter, by grouping them into single plot call for each.

Plotter group measurements/clutter into single plot call

---

stonesoup/dataassociator/tracktotrack.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py

This speeds up track to truth association by:
- avoiding looking at truths which start/end are after/before the
current timestep
- and maintaining an iterator for each truth to pick up from the
last timestep and search forward for a matching timestamp.

Speed up track to truth associator by avoiding searching of all times

---

stonesoup/reader/video.py

Video reader now has a timestamp attribute which is a DateTime object specifying the time of the first frame of the video. If it is None, then when the frame generator is called, it will be set to the current datetime. This prevents the timestamps of detections in the same detector object being changed by repeated calling of the iterator.

Fixing timestamps for the video reader

---

docs/demos/UAV_tutorial.py

Added keywords, as argument order changed in #427, causing this to add number of dimensions to rotation offset.

Fix UAV demonstration sensor parameters

---

docs/examples/Smooth_Platform_Coordinate_Transitions.py
docs/tutorials/01_KalmanFilterTutorial.py
docs/tutorials/02_ExtendedKalmanFilterTutorial.py
docs/tutorials/03_UnscentedKalmanFilterTutorial.py
docs/tutorials/04_ParticleFilter.py
docs/tutorials/05_DataAssociation-Clutter.py
docs/tutorials/06_DataAssociation-MultiTargetTutorial.py
docs/tutorials/07_PDATutorial.py
docs/tutorials/08_JPDATutorial.py
docs/tutorials/09_Initiators_&_Deleters.py

Issue seems related to specifying the thumbnail number as comment after `fig` lines. Moved to specifying the thumbnail number to last cell (but above any code)
Issue can be seen on recent builds on Read The Docs.

Fix missing thumbnails in sphinx gallery examples

---

stonesoup/types/orbitalstate.py

`orbitalstate` imports datetime class from the datetime module. `state` imports datetime module.
The OrbitalState class inherits State properties, which then causes a clash with generated docstrings, causing error for Sphinx 4.x.
Simple fix is having `orbitalstate` import datetime module instead.

Fix documentation build caused by type hints

---

docs/examples/Metrics.py
setup.py
stonesoup/models/base.py
stonesoup/models/measurement/tests/test_lg.py
stonesoup/simulator/simple.py
stonesoup/simulator/tests/test_detections.py
stonesoup/simulator/tests/test_groundtruth.py

Addresses the issue raised here
https://github.com/dstl/Stone-Soup/issues/396
Now all models that use random number generation have an optional seed that allows the user to, for example, always produce the same randomly generated truth data but allow other components to change between runs. 
Also needed to change the groundtruth paths to be an ordered set rather than a set in the groundtruth paths generator, otherwise the order that items were iterated through in the set would cause different results between runs. 
I added the seeds to the metrics example as well, as this was my test case and it makes sense that it should produce consistent results.
It would be useful if reviewers could make sure I haven't missed any models. I'd also appreciate a second opinion on the tests I wrote to …

User random seeds

---

stonesoup/measures.py
stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tracktotruthmetrics.py
stonesoup/tests/test_measures.py

Added the option to apply different maps to the groundtruth data and the state space in all the different measures. Also made changes to SIAPs metric generator to be able to use the new maps. 
If second map is not set, then it defaults to the same as the first map. This means all existing code still works. 
If you try to set the second map but not the first then it will raise an error. This is possibly something someone might want to do (i.e. not apply a map to the first space but apply a map to the groundtruth) so the error explains that this can be done by making the first map a list of all dimensions. The alternative would be to not make the second mapping default to the same as the first, which would make these changes not backwards compatible.

Multimap measures

---

stonesoup/simulator/transition.py

It doesn't seem to make any difference to current use cases (though I really don't know why, it seems like it should) but it was causing me some problems while implementing a new feature

Fixed an error in the angle calculations in smooth transition model maker

---

stonesoup/metricgenerator/metrictables.py

Figure sizes with tables in matplotlib are a bit of a dark art it seems, but these values seem to scale okay.
Related to #438 and #457

Fix figure size/scale for metrics tables

---

stonesoup/models/base.py

Deterministic use of random seeds was originally implemented in #444 in response to #396. However, when a model was not explicitly passed a random seed it would use a random value, which meant the run was not deterministic overall. This fixes that, using the change originally suggested in #396.
CC: @idorrington-dstl @sdhiscocks

Fix deterministic use of random seed

---

stonesoup/movable/movable.py

The previous check `time_interval != 0` would never be true (eg. timedelta(seconds=0) != 0).

Fix multi-transition platform loop

---

docs/tutorials/11_GMPHDTutorial.py

My previous GMPHD tutorial did not include a birth component. At first this was not a problem because the covariances of the priors were so large. But then in the review phase I changed those covariances to fix a plotting issue (the covariance ellipses were covering the whole graph, making it look like the graph had a background colour). This meant that the tracker would not pick up on new tracks. The birth component should be included to fix this mistake and to give the same output as using the PointProcessMultiTargetTracker.

Fix the GMPHD Tutorial to include the birth component

---

stonesoup/functions/__init__.py
stonesoup/functions/tests/test_functions.py
stonesoup/models/base.py
stonesoup/models/measurement/tests/test_lg.py

The jacobian() function needs to pass the **kwargs - this is needed for the nonlinear models which have a time component passed in. Also added the jacobian() to the Linear model - This simplifies handling when mixing Linear & Non-Linear models. One example is a coordinated turn with unknown turn rate (model is coming soon) in x,y plane and CV model in z-dimension.
This should also eliminate the need for a Linear Kalman model since the EKF with a Linear model will produce the same calculations.

Add jacobian() to Linear model and add kwarg handling to jacobian().

---

stonesoup/mixturereducer/gaussianmixture.py

In the GMPHD mixture reducer, sometimes there are multiple components (states) with the same tag. But in order to create tracks properly, the tags must be unique. When multiple states have the same tag, we want to assign the tag to the state that has the highest weight (as it is the most likely state to be part of the track). The rest of the states will get new tags. Previously, it accidently assigned the tag to the state with the lowest weight. To fix this, we just have to sort the components from highest to lowest weight instead of the default lowest to highest. Then we can keep the first one in the list and assign new tags to the rest of them.

Correct bug when dealing with duplicate tags

---

stonesoup/serialise.py
stonesoup/tests/test_serialise.py
stonesoup/writer/yaml.py

This shouldn't be a breaking change, as original class simply proxied existing methods anyway.
Also enable entry point to allow additional extensions to serialisation via entry point. This is to work over limitation of only being able to use one plugin at a time with ruamel.yaml, as well as allow easier integration with Stone Soup plugins.

Refactor YAML serialiser as ruamel.yaml plugin

---

stonesoup/measures.py
stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/mixturereducer/gaussianmixture.py
stonesoup/tests/test_measures.py

Squeezing arrays inside the `scipy.distance` functions has been deprecated in SciPy 1.7, and will raise error from SciPy 1.9

Pass 1d-arrays to scipy.distance

---

stonesoup/initiator/tests/test_wrapper.py
stonesoup/initiator/wrapper.py

To address #540 , the StatesLengthLimiter initiator wrapper now modifies a track's `metadatas` property to be a deque object, and limits the length to the same limit as the track's `states`.

Add metadatas limit to StatesLengthLimiter

---

.circleci/config.yml

This allows more flexibility to clear cache of dependencies in case of any build issues, or cache corruption.

Add cache version environment variable to CircleCI config

---

docs/examples/Smooth_Platform_Coordinate_Transitions.py
stonesoup/simulator/tests/test_transition.py
stonesoup/simulator/transition.py

Another method for calculating a series of smooth transitions between a series of target states, using a constant jerk (acceleration time derivative) model.

Add constant jerk model simulation for platforms

---

stonesoup/base.py
stonesoup/tests/test_repr.py

This change attempts to improve readability of repr output by lining up rows of NumPy arrays, separating objects with a new line as opposed to just a comma, and showing easily what is nested inside what by use of extra indentation.  
Additionally, [reprlib](https://docs.python.org/3/library/reprlib.html) is used to help impose limits on output size.  
In response to #474

Improve readability and limit size of repr output

---

stonesoup/movable/movable.py
stonesoup/movable/tests/test_movable.py
stonesoup/types/prediction.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py
stonesoup/types/update.py
stonesoup/updater/particle.py

The motivation behind this change is to allow the use of GroundTruthState types in platforms.
Previously, a platform's (movement controller's) `move` method hard-coded a standard `State` append.
This lead to loss of metadata when initiating a platform with a GroundTruthState, since the metadata property was not copied across to the new state.

Add method to copy prior state properties of a platform across to a new state

---

stonesoup/resampler/particle.py
stonesoup/resampler/tests/test_particle.py

This change is in response to #495 
The new ESSResampler class checks whether the ESS (Effective Sample Size) is below a given threshold before proceeding, otherwise simply returning the original particles without any resampling.

Introduce resampler that checks if resampling required

---

.circleci/config.yml
.codecov.yml
README.md
setup.py
stonesoup/base.py

Python 3.6 itself is no longer support, so no need to continue testing.
As dictionary order is now preserved, the base class no longer needs to be based on `OrderedDict`.

Drop Python 3.6 support

---

docs/examples/Metrics.py
docs/examples/ParticleFlow.py
stonesoup/metricgenerator/manager.py
stonesoup/metricgenerator/tests/test_basicmetrics.py
stonesoup/metricgenerator/tests/test_manager.py

This branch makes metrics return as a dictionary, with the keys being equal to `metric.title`.   
In response to #469.

Return metrics in a dictionary

---

stonesoup/types/hypothesis.py
stonesoup/types/tests/test_hypothesis.py

On checking equality between a `SingleProbabilityHypothesis` and `SingleHypothesis`, an error can be raised. Since the `ProbabilityHypothesis` __eq__ method simply checks whether the hypotheses' probabilities are equal. Since the `SingleHypothesis` has no `probability` attribute, an AttributeError is raised.
A simple fix is to check for type equality first.

Fix probability hypothesis equality check

---

docs/tutorials/11_GMPHDTutorial.py

Just a miniscule change to fix an error I found in tutorial 11.  The clutter was being generated over too small an area compared with the `meas_range`, which this should fix.

Fix a minor mistake with generating clutter in tutorial 11

---

docs/tutorials/09_Initiators_&_Deleters.py

This PR fixes an issue with Tutorial 09 on Initiators and Deleters, pointed out in Issue #591, which resulted in clutter being generated only when a TrueDetection was generated for a given truth.

Fix a bug in Tutorial 09

---

docs/demos/OpenSky_Demo.py
docs/examples/Moving_Platform_Simulation.py
docs/examples/Smooth_Platform_Coordinate_Transitions.py
stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py
stonesoup/models/base.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/transition/base.py
stonesoup/models/transition/linear.py
stonesoup/models/transition/nonlinear.py
stonesoup/models/transition/tests/conftest.py
stonesoup/models/transition/tests/test_ca.py
stonesoup/models/transition/tests/test_combined.py
stonesoup/models/transition/tests/test_ct.py
stonesoup/models/transition/tests/test_cts.py
stonesoup/models/transition/tests/test_nlct.py
stonesoup/models/transition/tests/test_nlcts.py
stonesoup/models/transition/tests/test_singer.py
stonesoup/models/transition/tests/test_singer_approximate.py
stonesoup/movable/tests/test_movable.py
stonesoup/platform/tests/test_platform_base.py
stonesoup/plotter.py
stonesoup/simulator/transition.py
stonesoup/types/tests/test_array.py

Added nonlinear constant turn models. Moved nonlinear class up into the model i.e. all models are inherently nonlinear. Linear models are a subclass. Added tests for the StateVectors class.
Replaced CombinedLinearGaussianTransitionModel and CombinedNonlinearGaussianTransitionModel with CombinedGaussianTransitionModel which is now in the base class. This will break a lot of existing code that used these combined models but it is an easy fix e.g. replace CombinedLinearGaussianTransitionModel with CombinedGaussianTransitionModel.

Add nonlinear constant turn models. Update transition model class hierarchy

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

A followup to close #588, we make the `measurement_model` attribute optional in initiators which are based on detections (namely the `SinglePointInitiator`, `SimpleMeasurementInitiator`, and `MultiMeasurementInitiator` classes). Detections are often paired with a measurement model, so the initiator will use that model in the new state. However, if the initiator is not given a measurement model and is passed a detection which also does not have a measurement model, it will raise a ValueError.
I have also made a test to ensure that the ValueError is raised correctly. I think there is no need to test the `MultiMeasurementInitiator` because the error will be raised in the `ExtendedKalmanUpdater` class, which is already tested. But I can add a test for this one as well if it would be best.

Make measurement model optional in measurement-based initiators

---

docs/demos/AIS_Solent_Tracker.py
docs/demos/OpenSky_Demo.py
docs/examples/Metrics.py
docs/examples/Sensor_Platform_Simulation.py
stonesoup/reader/yaml.py
stonesoup/tracker/base.py
stonesoup/tracker/pointprocess.py
stonesoup/tracker/simple.py
stonesoup/writer/tests/conftest.py

The trackers have been turned into iterables instead of generators. This allows trackers to be copied/ manipulated while producing tracks if needed.
Instead of `for time, tracks in tracker.tracks_gen():`
you now write
`for time, tracks in tracker:`
There _should_ be no other changes to how the trackers function

Trackers are Iterables instead of Generators 

---

stonesoup/models/measurement/nonlinear.py

Minor doc typo fixes on non linear measurement models

---

.github/workflows/docs-link.yml

Currently links are broken on new PRs due to change with CircleCI .

Update CircleCI artifacts redirector

---

stonesoup/updater/pointprocess.py

**TLDR:** Gaussian components updated using the `LCCUpdater` have weights which are `Probability` objects. This in turn causes some component state vectors to be made of Probabilities instead of floats. To fix this, we can cast the l1 correction term from a Probability to a float.
**Problem:** 
When using the GM-LCC filter, sometimes an updated component's state vector is filled with Probability types, instead of floats. For example, an updated component may have state vector 
`[Probability(15.0), Probability(0.5), 8.0, Probability(0.3)]`
On its own, this is not a big problem. But it isn't the proper use of a Probability object and none of the other filters behave this way.
**Cause:**
I traced the problem back and found that it was caused by two things:
The LCCUpdater calculates an l1 …

Cast correction term to float in LCCUpdater

---

docs/tutorials/11_GMPHDTutorial.py
stonesoup/hypothesiser/gaussianmixture.py
stonesoup/tracker/pointprocess.py
stonesoup/tracker/tests/test_pointprocess.py
stonesoup/types/state.py

Problem: In Gaussian-mixture based trackers, tracks can currently be made from the birth component without a detection. 
The `GaussianMixtureHypothesiser` creates prediction-detection pairs as hypotheses. Each prediction is paired with each `TrueDetection` and also with a `MissedDetection`. If the prediction is from the birth component, the hypothesis will get assigned a new tag. Otherwise, the hypothesis will carry the tag from the predicted component. But if the hypothesis is from the birth component with a `MissedDetection`, then it should not get a new tag. It should keep the "birth" tag because it does not correspond to any real data. This problem is realized later, when the `PointProcessMultiTargetTracker` checks the tag of each component. If a component does not have the 'birth' …

Prevent track from birth component w/o detection

---

docs/examples/MTT_3D_Platform.py

This is a supplementary example to be added to the online Stone Soup documentation. This example uses a platform-based simulation in 3D. A single, ground-based radar sensor attached to a stationary platform takes range/bearing/elevation measurements of airborne targets, represented using moving platforms with motion described by 3D CV models. Targets are birthed and die with 5% probability. The ground-based radar measures both true detections and clutter which is generated using the new ClutterModel implemented by @ekhunter123 in discussion #535. Track management processes are used in conjunction with a JPDA to perform 3D multi-target tracking on the randomly generated tracking scenario. Results are plotted in 3D using the new 3D visualization functionality added in #584. The GOSPA, SIAP, …

Create MTT 3D Platform example

---

LICENSE
docs/source/copyright.rst

This is required to ensure GitHub correctly identifies the license of the project.

Move contract reference from LICENSE file to documentation

---

docs/examples/Moving_Platform_Simulation.py

This doesn't make much difference in the actual example, but issue is apparent if for example you move sensors *x* position.

Fix plotting for Multi Sensor Moving Platform Simulator

---

stonesoup/simulator/simple.py

I added two parameters to the MultiTargetGroundTruthSimulator class. Together, these parameters give the user more control over the number of targets, and their locations, that exist in the simulation. Previously, the number of targets could only be controlled using the birth rate and death probability.
`preexisting_states` is a list of state vectors where the user wants a target to start. These targets will all be initiated at time 0 and will last at least 1 time step (they will not die at time 0). After that, their survival is random according to the death probability.
`initial_number_targets` is an integer dictating the number of targets that the user wants to be randomly created at time 0. This makes it possible to start the simulation with, for example, 10 targets randomly spread in …

Add option to specify number of targets in MultiTargetGroundTruthSimulator

---

docs/examples/ParticleFlow.py
docs/tutorials/03_UnscentedKalmanFilterTutorial.py
docs/tutorials/04_ParticleFilter.py
stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py
stonesoup/measures.py
stonesoup/metricgenerator/tests/test_plotter.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/platform/tests/test_platform_simple.py
stonesoup/plotter.py
stonesoup/predictor/particle.py
stonesoup/predictor/tests/test_particle.py
stonesoup/reader/tests/test_image.py
stonesoup/resampler/particle.py
stonesoup/resampler/tests/test_particle.py
stonesoup/tests/test_measures.py
stonesoup/types/particle.py
stonesoup/types/state.py
stonesoup/types/tests/test_particle.py
stonesoup/types/tests/test_prediction.py
stonesoup/types/tests/test_state.py
stonesoup/types/tests/test_track.py
stonesoup/types/tests/test_update.py
stonesoup/updater/particle.py
stonesoup/updater/tests/test_particle.py

Currently in stone soup we have a `ParticleState` which is not actually a state and contains `Particles` which have `StateVectors` and weights. This can make working with the particle filter a bit confusing as there are so many layers of particle types.
This pull request changes this structure so that everything needed is in the `ParticleState` and the `Particles` class has been removed. The new `ParticleState` contains `StateVectors` and weights meaning it can be substituted for anywhere that `Particles` was previously used.
`ParticleState` can be initiated using `StateVectors` and a sequence of weights or by using a list of particles (`Particle` types). 
This closes issue #537

Modify ParticleState so it has StateVectors and remove unnecessary Particles class

---

stonesoup/dataassociator/tests/test_tracktotrack.py
stonesoup/dataassociator/tracktotrack.py
stonesoup/hypothesiser/tests/test_gaussianmixture.py
stonesoup/measures.py

I've made some improvements to the track to track association algorithm.  The main difference is extra parameters allowing the user to specify whether the entire `StateVector` should be used, or rather just positional elements given in the `mapping` parameter.  The class was also renamed in anticipation of new T2TA algorithms in Stone Soup

Add options to track to track association algorithm

---

stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py

Currently the _RadarBearingRange_ and _RadarElevationBearingRange_ have no attribute to set its max range.
This PR adds a max_range, and adds in logic to only produce detections for states that lie within the sensor's FOV (similar to how _RadarRotatingBearingRange_ does it).

Add max range to simple Radars

---

stonesoup/mixturereducer/gaussianmixture.py
stonesoup/updater/pointprocess.py

This pull request fixes a few small bugs that are caused when dealing with Gaussian mixtures. Thanks to @sdhiscocks for your advice on this! I've described the fixes by filename:
**gaussianmixture.py:**
These are simple fixes - changing the and from a bitwise to a logical operator, and making the pruning threshold inclusive.
**pointprocess.py:**
Sometimes, a component will have a weight of 0. If the user has pruning off, the component can stay in the mixture. If this component then gets merged with another one, the merging process can result in a state whose mean and covariance are filled with NaN values. This problem is not immediately obvious, and only causes an error in the next time step in the hypothesiser. To be clear, it is fairly rare that this bug will actually cause a problem, …

Fix bugs when dealing with Gaussian mixtures

---

stonesoup/predictor/ensemble.py
stonesoup/predictor/tests/test_ensemble.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py
stonesoup/updater/ensemble.py

Similar to change in #581, this uses `StateVectors` as the `EnsembleState` state vector. As well as being more consistent, this also enables use of the vectorised models.

Modify EnsembleState to use StateVectors

---

docs/source/conf.py
stonesoup/sensor/action/__init__.py
stonesoup/sensor/action/dwell_action.py
stonesoup/sensor/actionable.py

Changes made so that the resolution of an ActionGenerator can be set manually when setting up an actionable sensor (rather than fixed at 1 degree for dwell_centre for example).

Fix ActionGenerator so resolution of actions available is not hard coded

---

stonesoup/simulator/simple.py

Apologies for missing this in my PR when I added this functionality to the MultiTargetGroundTruthSimulator. Small typo.

Fix typo in MultiTargetGroundTruthSimulator

---

stonesoup/predictor/particle.py

`control_input` doesn't match base class, and isn't used.

Fix incorrect arguments in particle predictor

---

stonesoup/resampler/tests/test_particle.py

test_ess_inequality will fail on some occasions due to floating point issues (you're essentially testing two floats for equality, which is never a good idea). Lowering the threshold to the default allows the test to pass.

test_ess_inequality fails sometimes

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

This PR adds the ability to pass custom arguments to figure initialisation as highlighted in #655. For example, `figsize` can be passed to Plotter in initialisation to change the figure size. 
Additionally, the method to set equal axes in 3d plots. This uses the data in the figure to set the axes.

Add additional functionality into Plotter class.

---

stonesoup/mixturereducer/gaussianmixture.py
stonesoup/mixturereducer/tests/test_gaussian_mixture_reducer.py

This can give significant performance benefits due to by default having to compare many of the mixture components to each other.

Add optional kDTree to Gaussian Mixture Reducer merge step

---

stonesoup/dataassociator/tests/test_tree.py
stonesoup/dataassociator/tree.py
stonesoup/hypothesiser/gaussianmixture.py
stonesoup/hypothesiser/tests/test_gaussianmixture.py

This enables use of kDTree with Gaussian Mixture Hypothesiser, adds ability to set tree search distance based on track covariance and fixes existing tree data associator tests.

Enable use of kDTree with Gaussian Mixture Hypothesiser

---

stonesoup/measures.py

This is in particular an issue with Particle States as calculating the mean can be costly.

Remove `hasattr` in Measures to avoid calling `mean` twice

---

docs/source/stonesoup.feeder.rst
docs/source/stonesoup.updater.rst
stonesoup/feeder/tests/test_track.py
stonesoup/feeder/track.py
stonesoup/updater/chernoff.py
stonesoup/updater/tests/test_chernoff.py

Following the work done in the example in my latest pull request #666, we've made standalone classes for the `ChernoffUpdater` and the `Tracks2GaussianDetectionFeeder`. I'd love any feedback or suggestions, thank you!
Thanks to @sdhiscocks for the help in designing and writing these classes!
Sample usages of both these classes can be seen in the example #666 .

Add ChernoffUpdater class and track feeder

---

stonesoup/updater/chernoff.py
stonesoup/updater/pointprocess.py

I have updated the documentation for the `ChernoffUpdater` class. This included editing the documentation to be clearer, and adding another reference. I also specified the parameters and returns of the class methods, following the style of the other update classes.
Second, I added another reference to the `PHDUpdater` class. This reference specifies the track management system that is used in the class, namely using track tags. This distinguishes it from the tree-based track management algorithms.

Update references and documentation of Updater classes

---

stonesoup/dataassociator/tests/test_tree.py
stonesoup/dataassociator/tree.py

As before, this still requires that all detections are using the same measurement model, otherwise a run time exception is raised.

Enable use of detections' measurement model in kDTree

---

stonesoup/types/_util.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py

This has significant performance improvements, for the trade off of limiting editing to state vector and weight of the ParticleState. However, they can still be replaced with another array, clearing the cache.
Minor issue is use of standard library `functools.cached_property` is only available from Python 3.8, so to maintain compatibility with Python 3.7, `cached_property` code snippet is also included.

Add caching of mean and covar on ParticleState

---

stonesoup/measures.py
stonesoup/mixturereducer/gaussianmixture.py

Multiple calls to Mahalanobis measure are common (e.g. comparing measurement predictions to detections), and by caching the matrix inversion, this can avoid repeating this costly operation.

Add Squared Mahalanobis distance and cache covariance matrix inversions

---

docs/source/conf.py
docs/source/doc_extensions.py
setup.py

A number of examples modify the seed when run, and this seed is then carried on into further examples currently. This may unintentionally fix the output of later examples, in particular when running all examples (e.g. CircleCI tests and Read the Docs).

Reset NumPy random state when running Sphinx-Gallery examples

---

docs/tutorials/12_InformationFilterTutorial.py
stonesoup/measures.py
stonesoup/plotter.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py

Added Information Filter tutorial. Fixed plotting for information states. Added Gaussian interface to the InformationState.

Add Information Filter Tutorial

---

docs/tutorials/sensormanagement/01_SingleSensorManagement.py
docs/tutorials/sensormanagement/02_MultiSensorManagement.py
docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
stonesoup/sensormanager/optimise.py

Add tutorial explaining the sensor managers which use the Scipy optimize library. This PR also includes some updates/improvements to the optimised sensor managers.

Add optimized sensor management tutorial

---

setup.py

Version 0.16.5 is needed to allow multiple types in ruamel.yaml.Yaml which serialise.py uses

Changed ruamel version requirement to 0.16.5

---

stonesoup/sensormanager/reward.py

This can be important in case of sensor handling obscuration, or limited resolution. It also offers a small performance benefit.

Modify uncertainty reward so sensors measure all tracks together

---

.circleci/config.yml
.readthedocs.yml
docs/ci-requirements.txt
docs/source/conf.py
docs/source/doc_extensions.py
docs/tutorials/01_KalmanFilterTutorial.py
docs/tutorials/02_ExtendedKalmanFilterTutorial.py
docs/tutorials/03_UnscentedKalmanFilterTutorial.py
docs/tutorials/04_ParticleFilter.py
docs/tutorials/05_DataAssociation-Clutter.py
docs/tutorials/06_DataAssociation-MultiTargetTutorial.py
docs/tutorials/07_PDATutorial.py
docs/tutorials/08_JPDATutorial.py
docs/tutorials/09_Initiators_&_Deleters.py
docs/tutorials/10_Simulation_&_Tracking_Components.py
docs/tutorials/11_GMPHDTutorial.py
docs/tutorials/12_InformationFilterTutorial.py
docs/tutorials/sensormanagement/01_SingleSensorManagement.py
docs/tutorials/sensormanagement/02_MultiSensorManagement.py
docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
setup.py
stonesoup/plotter.py
stonesoup/tests/test_plotter.py

This adds a new plotter based on `plotly`, which offers the same interface as the `matplotlib` one (interchangeable unless custom `matplotlib` commands have been used). These new plots introduce hover over info on states, ability to switch layers off/on, and easier ability to zoom and pan, etc.
The tutorials have been updated to use `plotly` based plotter.
One minor issue is thumbnails may not be produced locally without additional dependency `kaleido`, which I've left as optional but included in the CircleCI and Read the Docs build.
Also tested on Read the Docs to confirm build.

Add new plotter based on plotly

---

stonesoup/sensormanager/reward.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py
stonesoup/types/track.py

This gives similar behaviour to a standard list

Enable proper shallow copying of state mutable sequences

---

docs/source/index.rst

I've recently tried to install StoneSoup using the provided `python -m pip install -e .[dev]` command, and it didn't work. I've found out, that when using `zsh`, the location and the extra have to be enclosed by quotation marks. For the sake of other `zsh` users, I think a quick instruction could be given in the docs.

Update install instructions to make compatible with zsh

---

stonesoup/plotter.py

- Use marker style for `matplotlib` plotter to signify state type, related to #695 
- With `plotly` ensure that if custom marker provided, that it is not overwritten,
and update documentation to reflect default

Update marker styles for tracks in plotters

---

stonesoup/dataassociator/tests/conftest.py
stonesoup/gater/tests/test_distance.py
stonesoup/hypothesiser/probability.py
stonesoup/hypothesiser/tests/test_composite.py
stonesoup/hypothesiser/tests/test_probability.py

This adds the ability to use nonparametric PDA for clutter spatial density, where it is estimated based on assumption that measurements within a defined validation region represent the clutter level.
This change also gates out non valid measurements by default, similar to the behaviour in the `DistanceHypothesier`, and per description in original PDA paper.

Add Nonparametric PDA and gate out non valid measurements

---

stonesoup/dataassociator/_assignment.py
stonesoup/dataassociator/neighbour.py

Previously this used iteration rather than indexing. By changing to using indexing and vectorising some calculations, gives a performance benefit for large number of tracks/detections.
Performance difference isn't noticeable on a small cost matrix, but testing on a `(1988, 4808)` cost matrix results in identical output with ~50x to 60x speed up.

Modify assign2D to exploit NumPy indexing

---

stonesoup/base.py
stonesoup/tests/test_declarative.py

This avoids the need to first get the signature and avoid more complex bind method which handles things like positional only and keyword only arguments which aren't relevant.
This offers a small performance improvement.

Directly set arguments when instantiating a class

---

stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py

This gives a performance boost as sampling multiple noise points is much more efficient.
There is possibility of a model using a frozen distribution, but there is issue with this currently doing matrix decomposition for every call, meaning little benefit of doing this.
As an example, currently this reduces calls to `rvs` method from 11.8s to 0.2s in the ADS-B tracking demo.

Pre-fetch noise values for sensor measure method

---

stonesoup/base.py

I haven't manged to write a test which fails with the old logic and passes with the new, but in testing other things I spotted this logic error, so thought it should be fixed. 
It has no effect on functionality that I can detect.

Improve logic of readonly property checking to avoid double settting

---

stonesoup/dataassociator/tree.py

This was caused by tuple being assumed to be 2d-slice.

Fix mapping in TPR tree causing error when mapping is tuple

---

stonesoup/plotter.py

This was caused by squeeze removing extra dimension when only a single state was present. Using concatenate along correct dimension avoids this.

Fix plotting error when a track only has a single state

---

stonesoup/sensormanager/reward.py

Current reward function assumes a single detection per track. This adds an instance check to manage when clutter (or non TrueDetection types) is present.

Add instance check for reward function

---

docs/source/stonesoup.reader.rst
setup.cfg
stonesoup/reader/hdf5.py
stonesoup/reader/tests/test_hdf5.py

Borrowed from the generic CSV readers to support HDF5 files, adding the option to reduce the resolution of time fields while reading data in.

Implement generic readers for HDF5

---

docs/source/conf.py

A new feature, enabled by default, in Sphinx includes object entries in table of contents, which is too verbose. Disabling to keep previous behaviour.

Disable documentation table of content entries for objects

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

For some Gaussian states the uncertainity can't be plotted by the `Plotter` class. You can see if you try running the following code
```
from stonesoup.plotter import Plotter
from stonesoup.types.track import Track
from stonesoup.types.state import GaussianState, StateVector
track = Track([GaussianState(state_vector=[0, 0], covar=[[10, -1], [1, 10]])])
Plotter().plot_tracks(track, mapping=[0, 1], uncertainty=True)
```
This is caused by complex eignevalues or eigenvectors from the uncertainity matrix. I've put in a check for these in the `Plotter` class. States which cause complex eignevalues or eigenvectors are now skipped in the plot_tracks function and a warning is raised. A test has been created for this behaviour

Fixed TypeError being thrown on certain Gaussian states in the Plotter.plot_tracks function

---

stonesoup/functions/__init__.py
stonesoup/functions/tests/test_functions.py

Dotproduct function previously only worked with `StateVector`. This is designed to make it work with `StateVectors` and return an numpy.array of dimension 1x the number of `StateVector`s.

Modified dotproduct to work with StateVectors 

---

stonesoup/models/base.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/resampler/particle.py
stonesoup/types/numeric.py
stonesoup/types/state.py
stonesoup/types/tests/test_numeric.py
stonesoup/updater/particle.py

This avoids a number a nugatory calculations switching in/out of log space with Probability class.
Also modified mean/covar calculation in particle state to use float array to avoid similar issue caused by Probability class forcing use of object arrays.

Add logpdf method to models, and implement in particle filter

---

.gitignore
docs/examples/TimePlotterExample.py
stonesoup/plotter.py

- Use all timestamps by default for TimeBasedPlotter
This no longer requires specifying the time stamps, as they default to
those from data being plotted
- Simplify docs for Notebook use of animations in TimeBasedPlotter
Also ignore example gif file that is saved.

TimeBasedPlotter default timestamps and Notebook animation docs

---

stonesoup/sensormanager/optimise.py

This was causing issues with latest version of NumPy/SciPy with `Angle` type.

Ensure ranges are floats in optimise sensor manager

---

stonesoup/models/transition/linear.py

Fixed covar calculation of constant nth derivative. Line 150 had “N**2”, corrected to “N*2”.

Fix covar for ConstantNthDerivative model

---

docs/tutorials/04_ParticleFilter.py

This pull request is to assess issue #682 of adding the ESS resampler to the particle filter tutorial.

Add ESS Resampler to particle filter tutorial

---

stonesoup/functions/__init__.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/platform/tests/test_platform_base.py

The rotation matrix is currently formed backwards as rotz(theta_z) @ roty(theta_y) @ rotx(theta_x). It needs to be in reverse order: x, y, z. This is because matrix @ operations are carried out from right to left and we need to rotate about z first, because only then can we know which way to rotate about y. This branch implements that and adds some test cases to prove it (some of which fail with the previous code). 
This does lead to a problem with Bearing, as discussed in Issue #749.

Rotation matrix fix

---

stonesoup/types/angle.py
stonesoup/types/tests/test_angle.py

Address part of issue #749 that deals with `Bearing`s not playing nicely with `numpy.isclose`, which is due to `abs(Bearing(-pi))` returning a negative value.

Fix Angle.__abs__ such that it always returns a positive value

---

stonesoup/platform/tests/test_platform_base.py

Use Bearing type to handle wrapping
This was failing on CircleCI due to not handling azimuth not being exactly equal to `-np.pi` (off at 8th decimal place or something.).

Fix test comparing platform angles close to ±π

---

stonesoup/plotter.py

When plotting tracks, the previous behavior would draw a line between all of the states that weren't of type Update.

Do not draw line between not_update states.

---

docs/tutorials/filters/GMPHDTutorial.py
stonesoup/mixturereducer/gaussianmixture.py

Added a little more detail to the doc for `GaussianMixtureReducer` properties. Looks like my IDE also removed trailing whitespaces, hope that isn't an issue.

Add more documentation for GaussianMixtureReducer.

---

stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py

Implemented an analytic expression for the Jacobian of CartesianToElevationBearingRangeRate. This is a more-accurate calculation than the baseline numerical Jacobian calculation. Also, on my system, this sped up the calculation from 500 usec to 100 usec.

Implement analytic Jacobian for CartesianToElevationBearingRangeRate.

---

docs/examples/Creating_Actionable_Sensor.py
docs/examples/range_range_rate_binning.py
docs/tutorials/filters/ASDFilter.py
stonesoup/models/measurement/linear.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_combined.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/updater/tests/test_alphabeta.py

Cast the noise_covar value to a CovarianceMatrix when initialising a MeasurementModel in LinearGaussian & NonLinearGaussianMeasurement
Fixed the changes to RangeRangeRateBinning testing

Cast noise_covar value to a CovarianceMatrix when initialising a MeasurementModel 

---

stonesoup/reader/tests/test_astronomical.py

Avoids creating `test.fits` in repo directory when running tests.

Use temporary file for FITS Reader tests

---

stonesoup/types/array.py
stonesoup/types/tests/test_array.py

Previously unusable due to incorrect arguments being passed

Fix np.mean for StateVectors

---

docs/source/stonesoup.regulariser.rst
docs/source/stonesoup.rst
stonesoup/regulariser/__init__.py
stonesoup/regulariser/base.py
stonesoup/regulariser/particle.py
stonesoup/regulariser/tests/test_particle.py

Created the regulariser object for optional use with particle filters when impoverishment is a problem. This has included the class MCMCRegulariser that follows a particular implementation using the Metropolis-Hastings algorithm (referenced appropriately in the docs).

Create regulariser object and MCMC particle regulariser

---

stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py
stonesoup/sensor/sensor.py

Used to detect if clutter generated by the ClutterModel is in the FOV.
Resolves #781

Add is_clutter_detectable method to sensors

---

docs/examples/Track_Stitcher_Example.py

Previously the example used a multi measurement initiator, which held an internal state, which would impact generation of sample tracks for stitching.

Change track stitching example initiator

---

docs/examples/Multi_Tracker_Example.py

Example that compares multiple trackers against one set of detections.

Add multi_tracker_example

---

docs/tutorials/dataassociation/KDTree_Tutorial.py

Sometimes the build failed due to example taking too long to run. I've reduced the number of tracks in simulation, and avoided running simulation multiple times.

Fix issue with kD-tree example not building

---

stonesoup/base.py
stonesoup/tests/test_declarative.py

Forward declaration of type hints is a method to allow type checking in instances where a full import would cause a problem, for example commonly an error due to a circular import. See `typing.TYPE_CHECKING` on the [python docs](https://docs.python.org/3/library/typing.html) for more information. 
This may not be the neatest solution, as it allows any type hint declared as a string. Ideas for improvement are welcome, but this is functional at least.

Enable Forward Declaration of Type Hints for Properties

---

stonesoup/dataassociator/mfa/__init__.py
stonesoup/dataassociator/tests/test_mfa.py

Previously this raised an error, rather than returning the expected results of no associations

Handle case of no tracks with MFA

---

stonesoup/predictor/particle.py
stonesoup/predictor/tests/test_particle.py
stonesoup/types/orbitalstate.py
stonesoup/types/prediction.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py
stonesoup/types/track.py
stonesoup/types/update.py
stonesoup/updater/particle.py
stonesoup/updater/tests/test_particle.py

Introduced the `BernoulliParticlePredictor` and `BernoulliParticleUpdater` as a new joint detection and tracking single target tracker. The `BernoulliParticleState` has been introduced, as well as the prediction and update variants. 
The `Regulariser` has been added as an optional property to the `ParticleUpdater` class but is only implemented in the `BernoulliParticleUpdater` currently. 
A try and except statement has been added to the `_update_metadata_from_state` method in the Track class to skip the incorporation of metadata from detections into the track object when `MultipleHypothesis` is populated with unordered `SingleHypothesis`.
Here is a gist to demonstrate the use of the tracker: https://gist.github.com/timothy-glover/ae9d5a748604d6bbc12391ff03357af7.

Bernoulli Particle Filter

---

docs/tutorials/sensormanagement/01_SingleSensorManagement.py
docs/tutorials/sensormanagement/02_MultiSensorManagement.py
docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py

Add sensor field of view to plot animations

Plot FOV on Sensor Management tutorials

---

stonesoup/functions/__init__.py

Added option to mod_elevation to counter edge case where elevation returns == 2*pi, rather than 0.

Fix edge case with mod elevation for 2π

---

stonesoup/base.py

This PR aims to fix #831 by avoiding the recursive call to `BaseRepr.whitespace_remove()`.

Fix recursion error when printing objects

---

stonesoup/tracker/simple.py
stonesoup/tracker/tests/test_simple.py

This PR adds this class:
`- SingleTargetMixtureTracker`
This class helps to deal with the single target tracking using a probability data associator like PDA because, currently, using `SingleTargetTracker` would have ended in an error. This component is built following the `MultiTargetMixtureTracker` structure.
An example can be [found here](https://gist.github.com/A-acuto/6a5c634a39248015b0a428d8005e12c3)

Add a SingleTargetMixtureTracker

---

stonesoup/dataassociator/_assignment.py
stonesoup/dataassociator/tests/test_assignment.py
stonesoup/dataassociator/tests/test_tracktotrack.py
stonesoup/dataassociator/tracktotrack.py
stonesoup/metricgenerator/basicmetrics.py
stonesoup/metricgenerator/tests/test_basicmetrics.py
stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tracktotruthmetrics.py
stonesoup/types/association.py
stonesoup/types/interval.py
stonesoup/types/tests/test_association.py
stonesoup/types/tests/test_detection.py
stonesoup/types/tests/test_interval.py
stonesoup/types/tests/test_metric.py
stonesoup/types/tests/test_time.py
stonesoup/types/time.py

Created a new `CompoundTimeRange` class, a container class for `TimeRange`.  This allows much greater flexibility for association objects, for example to associate two objects between the ranges [a,b] and [c,d] in a single `TimeRangeAssociation`.  
New additions were made to the `AssociationSet` class mainly to reflect these changes.  
The last main change was the new `multidimensional_deconfliction` algorithm.  This is a very rudimentary but hopefully functional algorithm to ensure an `AssociationSet` has no associations that conflict - we can't have two different associations involving the same object at any given time.  The algorithm is very basic, simply using the total length of an association as a proxy for strength of association, but I believe the groundwork has been laid to …

One to one Assignment for Association

---

stonesoup/plotter.py

A quick PR. Changes ellipse plotting so that the first point is appended to the end of the list of ellipse points so that, if the outline of an ellipse is plotted, the outline draws the proper shape.
Before:
After:

Fix ellipse plot

---

stonesoup/predictor/particle.py
stonesoup/regulariser/particle.py
stonesoup/regulariser/tests/test_particle.py
stonesoup/types/multihypothesis.py
stonesoup/updater/particle.py
stonesoup/updater/tests/test_particle.py

The prior used for the `MCMCRegulariser` should be projected through time without the inclusion of noise. To do this, `transition_model` has been added as a property of the MCMCRegulariser. The transition model is used to propagate the prior particles at the beginning of the `regularise()` method. The support for lists of type `Particle` has also been dropped to allow for the calculation of the time interval in the `regularise()` method.

Regulariser amendment and implementation in ParticleUpdater

---

docs/tutorials/sampling/ResamplingTutorial.py

Final plot in Resampler tutorial was displaying the CDF of full particle weights. This change makes it display the CDF of the residual weights.

Change plot in Resampler Tutorial to display correct CDF

---

stonesoup/plotter.py

Added `hide_plot_traces` to the Plotterly class. This allows certain plotting elements to be hidden as default. The user can toggle there visibility. This can help highlight aspects of a graph in the documentation.
Added `mapping` to `plot_sensors` in Plotterly and Plotter class. Previously the mapping was hard coded to [0, 1]. The mapping is now softcoded with a default value of [0, 1] to avoid breaking anything

Add Mapping to plot_sensors. Hide plotting elements in Plotterly

---

docs/tutorials/01_KalmanFilterTutorial.py
stonesoup/models/transition/nonlinear.py

I found a few bugs in the `ConstantTurn` transition model, which this PR aims to fix. 
1.  As detailed in #841, the documentation for `Q_t` did not match the implementation. 
2.  The bottom right term in the `Q_t` array was erroneously divided by the change in time, which would result in the noise of the turn rate being smaller for a larger change in time. I'm not really sure personally why this value is not instead **multiplied** by _dt_, but this seems to be a misunderstanding on my part and not a mistake. 
3. There was an issue where if you put in an integer turn rate of zero, you would get an error for division by zero. This is a little bit academic as it's not really the intended use for this transition model, but I thought it was worth fixing for consistency. 
I have also raised up …

Fix non linear constant turn transition model

---

docs/examples/MTT_3D_Platform.py
docs/examples/Metrics.py
docs/examples/Multi_Tracker_Example.py
docs/examples/ParticleFlow.py
docs/examples/Track2Track_Fusion_Example.py
docs/examples/Track_Stitcher_Example.py
docs/tutorials/sensormanagement/01_SingleSensorManagement.py
docs/tutorials/sensormanagement/02_MultiSensorManagement.py
docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
stonesoup/metricgenerator/basicmetrics.py
stonesoup/metricgenerator/manager.py
stonesoup/metricgenerator/metrictables.py
stonesoup/metricgenerator/ospametric.py
stonesoup/metricgenerator/pcrbmetric.py
stonesoup/metricgenerator/plotter.py
stonesoup/metricgenerator/tests/conftest.py
stonesoup/metricgenerator/tests/test_basicmetrics.py
stonesoup/metricgenerator/tests/test_manager.py
stonesoup/metricgenerator/tests/test_ospametric.py
stonesoup/metricgenerator/tests/test_pcrbmetric.py
stonesoup/metricgenerator/tests/test_plotter.py
stonesoup/metricgenerator/tests/test_tables.py
stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tests/test_uncertaintymetric.py
stonesoup/metricgenerator/tracktotruthmetrics.py
stonesoup/metricgenerator/uncertaintymetric.py
stonesoup/plotter.py

- Have replaced SimpleManager metric manager with new MultiManager class so this will be a breaking change. 
- MultiManager can take multiple metric generators of the same type and multiple sets of the same type to generate metrics. 
- All metrics that take in track and truth can now also take in 2 tracks.
- Additional functionality added to MultiManager through new methods to help easier extraction of metrics and insights.
- New MetricPlotter class created to make plotting metrics easier.
Update:
- Have added SimpleManager metric manager back in to avert breaking change. It should operate in the same way as before.

Add metric MultiManager and MetricPlotter

---

stonesoup/regulariser/particle.py
stonesoup/regulariser/tests/test_particle.py
stonesoup/updater/particle.py
stonesoup/updater/tests/test_particle.py

This PR has introduced the optional property `constraint_func` to `ParticleUpdater` and `MCMCRegulariser`. If defined, this is intended to enforce that particle states should not exceed certain values by modifying the associated weights, increasing the likelihood of resampling. Here the constraint function should accept a `ParticleState` type and return a logical index of particles that exceed the defined constraints. An example of this can be seen here:
https://github.com/timothy-glover/Stone-Soup/blob/7ae343e147176107a35fafa81c00c2a7d879561e/stonesoup/regulariser/tests/test_particle.py#L16-L18
A bug was also spotted in the test for the `ParticleUpdater`. The original line, seen below, was passing regardless of what the weights are. This has been replaced with a check to ensure the sum …

Introduce ability to constrain particle states in ParticleUpdater and MCMCRegulariser

---

stonesoup/dataassociator/_assignment.py
stonesoup/dataassociator/tracktotrack.py

Associations expect objects to be in a set, not a tuple. OrderedSet has been used to preserve order which may be useful.

Fix track to track associations type

---

stonesoup/feeder/tests/test_track.py
stonesoup/feeder/track.py

Change Tracks2GaussianDetectionFeeder return type to a set.
Previously this was a list which isn't the correct type for detection
feeders.
Also added `track.id` to metadata on detection as this can be useful to trace source of detection.

Change return type and add track ID metadata to Track2GaussianDetectionFeeder

---

stonesoup/resampler/particle.py
stonesoup/updater/particle.py
stonesoup/updater/tests/test_particle.py

This PR adds the functionality that prevents regularisation from happening if resampling has not been performed. Since the regularisation process is intended to prevent particle impoverishment as a result of resampling. Performing regularisation when resampling has not been performed may lead to unnecessary particle spreading. The changes in the PR check to see if the `ParticleState` object is the same before and after resampling. This check prevents negates the problem where a `Resampler` is defined but the resampling process has not been performed due to the effective sample size threshold not being met. If changes have occurred then the `Regulariser` will be used if it has been defined. 
The changes have been made here in such a way that will allow regularisation to occur if a …

Resampling dependant regularisation in ParticleUpdater

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

`NoHistoryMultiMeasurementInitiator` was created so track metrics wouldn’t take into account the part of the track that was in ‘holding’. ‘Holding’ tracks aren’t available to the tracker. When a holding track is upgraded to a full/sure track it takes its history with it. When assessing tracks post-simulation with metrics the full history is used which can be misrepresentative.
An option was added to skip measurements that don’t have a `ReversibleModel` measurement model in `MultiMeasurementInitiator`

Minor Addition and Changes to MultiMeasurementInitiator

---

docs/source/stonesoup.functions.rst
stonesoup/functions/interpolate.py
stonesoup/functions/tests/test_interpolate.py

The function will take a `StateMutableSequence` and a `times: List[datetime.datetime]`. The function will create a new `StateMutableSequence` with states only at the times specified by `times`.
This time with a clean git history. See #865 for messy history
This provides a step for fixing #364

Function to linearly interpolate state mutable sequences

---

docs/examples/EnsembleFilterExample.py
docs/source/stonesoup.updater.rst
stonesoup/updater/ensemble.py
stonesoup/updater/recursive.py
stonesoup/updater/tests/conftest.py
stonesoup/updater/tests/test_ensemble.py
stonesoup/updater/tests/test_recursive.py

Added new updaters that use calculated posterior state estimates as a prior to run recursively for n steps. Additionally, a new ensemble updater with an inflation step as a building block for a recursive version.
New updaters:
- `BayesianRecursiveUpdater` (BRUF, code by SDHiscocks)
- `RecursiveEnsembleUpdater`
- `LinearisedEnsembleUpdater` (A building block for the following)
- `RecursiveLinearisedEnsembleUpdater`
Tests added for all updaters.
As well as the new updaters, I have included an example document for the Ensemble Filter in this pull request.

New Recursive updaters added

---

docs/examples/Polar_Plotting.py
stonesoup/plotter.py
stonesoup/types/angle.py

Create polar plots using plotly like [this](https://plotly.com/python/polar-chart/)

Polar Plotting

---

stonesoup/updater/recursive.py

Fix to RecursiveEnsembleUpdater to recalculate measurement_prediction at every iteration.
As the measurement_prediction is calculated before the recursive loop, self.check_measurement_prediction was not recalculating the measurement prediction at every iteration. I have added an extra step to remove the measurement prediction at every step so that it is recalculated.

Fix to RecursiveEnsembleUpdater

---

docs/examples/Track2Track_Fusion_Example.py

This utilises `itertools.tee()` in order to replicate the iterators from components like simulators, trackers and detectors, for use later on. This avoids need for `DummyDetector` and calls to `iter`.
Also use longest track in track2track fusion example plot, as sometimes randomly chosen example is very short.

Modify track fusion example to use tee and plot longest track

---

docs/tutorials/sensormanagement/02_MultiSensorManagement.py
docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py
stonesoup/sensor/action/dwell_action.py
stonesoup/sensor/action/tests/test_dwell_action.py
stonesoup/sensor/actionable.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/tests/test_actionable.py
stonesoup/sensormanager/tests/conftest.py

ActionableProperties have "generator_kwargs" dictionary which maps properties of the ActionGenerator, to properties of the Sensor. This removes the "resolutions" property from all Actionables and allows properties of the ActionGenerator to be set via the Sensor.

Change how sensor parameters are passed to action generators

---

stonesoup/predictor/kalman.py
stonesoup/updater/kalman.py

Changing default to `None` sets it to `3 - Ns` as described.
Closes #900

Correct UKF kappa default to match documentation

---

docs/examples/EnsembleFilterExample.py
stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py
stonesoup/types/state.py

Increase tolerance on initiator test for ensemble filter, as these were failing fairly frequently due to random sampling.
Modification for sampling on Ensemble state makes it similar to other sampling done in models, as well as supporting custom data types (e.g. Bearing) properly.

Modify Ensemble state generation and initiator test thresholds

---

stonesoup/predictor/kalman.py
stonesoup/updater/kalman.py

Adapted the square root version of the Kalman predictor and updater to inherit from the extended, rather than standard, counterparts. This gives them access to `jacobian()` which means non-linear models can now be used. Previously an error would be chucked.

Adapted the square root components

---

docs/tutorials/sensormanagement/01_SingleSensorManagement.py
docs/tutorials/sensormanagement/02_MultiSensorManagement.py
docs/tutorials/sensormanagement/03_OptimisedSensorManagement.py

When building the docs to test changes, the sensor management tutorials take the longest to load by far. Shortening their length from 50 to 20 shortens the loading time without compromising on the information - it is still clear that the brute force sensor managers far outperform the random one.

Shorten sensor management tutorials' simulation length

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

This PR adds the functionality to set the title of an AnimationPlotter plot.
This solves Issue #858.
Usage:
```
plotter = AnimationPlotter(title="Plot Name")
plotter.plot_ground_truths(truth, [0, 2])
plotter.run()
```

Adding setting title functionality to AnimationPlotter

---

stonesoup/metricgenerator/plotter.py

Add the `Plotter.plot_measurements` method's `convert_measurements` parameter to the metric plotter `TwoDPlotter` `plot_tracks_truth_detections` method.

Add convert measurement parameter to TwoDPlotter

---

stonesoup/metricgenerator/ospametric.py
stonesoup/metricgenerator/tests/test_ospametric.py

Fixes issue described in https://github.com/dstl/Stone-Soup/issues/897 
Adds the switching term to the GOSPA as outlined in https://github.com/dstl/Stone-Soup/discussions/876

Added the switching term to GOSPA.

---

stonesoup/models/control/base.py
stonesoup/models/control/linear.py
stonesoup/models/control/tests/test_control.py
stonesoup/predictor/information.py
stonesoup/predictor/kalman.py

Problem: current control models, both in their stand-alone state and as part of the predictor, are somewhat peculiar (that's my fault). This change is designed to make them look a bit more like other models, and so hopefully make their use more intuitive. 
See here for an example of use: https://gist.github.com/jmbarr/1f9cfb06eea9dd051bb7adea9f75d3a8
Should have implications for sensor and platform management.

Simplify (or at least make more standard) control models

---

docs/examples/Custom_Pandas_Dataloader.py
stonesoup/functions/__init__.py
stonesoup/metricgenerator/ospametric.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_gas.py
stonesoup/platform/tests/test_platform_base.py
stonesoup/plotter.py
stonesoup/predictor/tests/test_particle.py
stonesoup/reader/generic.py
stonesoup/reader/kafka.py
stonesoup/reader/pandas_reader.py
stonesoup/sensor/action/dwell_action.py
stonesoup/serialise.py
stonesoup/tests/test_serialise.py
stonesoup/types/array.py
stonesoup/types/state.py
stonesoup/updater/particle.py
stonesoup/updater/tests/test_particle.py

Upcoming NumPy 2 release has a number of breaking changes, which are fixed in this PR. This has been tested against latest nightly builds of NumPy, SciPy and matplotlib.

NumPy 2 compatibility

---

stonesoup/plotter.py

Enables use of Plotterly zoom without having to be a rectangle.

Tidy plotter initialisation and remove rectangle zoom restriction.

---

.gitignore

Added in Sphinx Gallery 0.15.0 as output

Ignore Sphinx Gallery execution times file

---

stonesoup/reader/tests/test_astronomical.py
stonesoup/types/tests/test_orbital.py

Tests are now skipped if astropy is missing.

Avoid test collection failure with optional dependency astropy

---

docs/examples/Polar_Plotting.py
stonesoup/plotter.py
stonesoup/tests/test_plotter.py

This PR gives the option of plotting in 3D using Plotterly. It also adds more tests and makes dimension checking in Plotterly more holistic. More details are:
- Plotting is now supported in 3D for ground truth, measurements, and tracks. Sensor plotting is not here but no reason why it can't be added in the future.
- Dimension checking has been simplified so that integers can always be used in cases like `if self.dimension == 1:`
- Track uncertainty has been added in the way of error bars in the x, y, and z direction, as suggested by @Carlson-J [here](https://github.com/dstl/Stone-Soup/pull/887/commits/2ee65f3b3622ebeef784a12647bc386d96388e6b). It is not perfect because it does not show times where covariance is large, but it's a simple way of getting an idea of track uncertainty. It makes …

Add 3D plotting option to Plotterly

---

stonesoup/plugins.py

The dictionary like interface was dropped in Python 3.12. Changes here attempt to use newer interface (`group` keyword argument from Python 3.10), and fall back to old interface (`dict`) if error is raised.

Fix plugins for latest versions of Python

---

.circleci/config.yml
stonesoup/dataassociator/tests/test_probability.py
stonesoup/plugins.py

This enables us to flag plugin compatibility issues as well as enable tests for the Stone Soup plugin system

Add pyehm plugin as optional tests

---

setup.cfg

``stonesoup.plotter.Plotterly`` uses the 'legendrank' key word which was only introduced in [plotly 5.0.0](https://github.com/plotly/plotly.py/releases/tag/v5.0.0). Therefore the Plotly requirement needs a version designator.

Added Version Requirement for Plotly

---

stonesoup/updater/kalman.py
stonesoup/updater/recursive.py
stonesoup/updater/tests/test_recursive.py

This pull request is an extension of PR #889. #889 will be closed as it is superseded by this.
New Updater classes:
- VariableStepBayesianRecursiveUpdater
- ErrorControllerBayesianRecursiveUpdater
Extensions of the BayesianRecursiveUpdater. Unlike how the BayesianRecursiveUpdater uses equal measurement noise for each recursive step, the VariableStepBayesianUpdater over-inflates measurement noise in the earlier steps, requiring the use of a smaller number of steps. The ErrorControllerBayesianRecursiveUpdater is a further extension in which error control parameters are introduced.

Error-Controller BRUF and Variable-Step BRUF

---

stonesoup/hypothesiser/probability.py
stonesoup/types/numeric.py
stonesoup/types/tests/test_numeric.py

In general when you multiply a value by a probability you shouldn't get a probability. This is what the overwritten `__mult__()` method is doing. Hence if `a = Probability(0.3)*5.0`, `a = Probability(1.5)` which doesn't make sense. This fixes that to return a float unless the input is `Probability` in which case return `Probability`.
There may also be a discussion to be had about preserving the class of the value by which the probability is multiplied, using `value.__class__(prob*value)` or something, but that runs a little against allowing Python to do its thing. And it creates problems with integers. But it might fix a problem by which StateVectors of size (1,1) are reduced to floats.

Fixing bug which causes multiplication by Probability to return a Probability

---

docs/source/stonesoup.updater.rst

Quick fix to add `stonesoup.updater.iterated` module to the documentation

Add iterated module to documentation

---

stonesoup/metricgenerator/ospametric.py

There was an issue converting a list of `ParticleState` objects into a numpy array. This pull request fixes this by replacing 
```np.array(measured_states)[meas_mask]```
with
```
meas_points = np.empty(len(measured_states), dtype="O")
meas_points[:] = measured_states
meas_points = meas_points[meas_mask]
```

Fixing GOSPA metric to work with ParticleState

---

docs/examples/KalmanFilterOOSMExample.py

This PR adds a simple example of using a Kalman Filter with measurements with a fixed delay from a sensor.
As referenced by #940 and #939 , this is a series of examples that shows different methods to deal with OOSM. 
The example has been modified by adding a EK filter for comparison.

Example of Ensemble Kalman filter with Out-Of-Sequence measurements

---

stonesoup/measures/state.py

The original implementation of input checking for the Kullback Leibler divergence measure used `len()` on the `state.particles` object, slowing down execution for the measure and usage in sensor management. The check has been changed in this pull request to use `len()` on the `state` object itself. This change has also reduced the time taken to complete sensor management tests, perhaps removing the requirement of the `--slow` marker.

Change ParticleState Length check in KLD measure for efficiency

---

docs/source/stonesoup.initiator.rst
stonesoup/initiator/particle.py
stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_particle.py
stonesoup/initiator/tests/test_simple.py
stonesoup/updater/particle.py

This PR adds the following components:
- ``SMCPHDInitiator``: A particle initiator that initiates tracks using a SMCPHD Predictor/Updater pair
- ``ParticleGaussianInitiator``: A wrapper that converts ``ParticleState`` based tracks to ``GaussianState`` based equivalents.
Here is a [gist](https://gist.github.com/sglvladi/0bfc78430d8ad66fd8882859acbf1185) that demonstrates both classes in action.

Add SMC-PHD initiator implementation

---

stonesoup/gater/distance.py
stonesoup/gater/tests/test_distance.py

Data association in stone soup occurs in the measurement state space. This pull request introduces `TrackingStateSpaceDistanceGater`, a gater than operates in the tracking state space (not the measurement state space). As the gate is in the tracking state space, measurements must use a measurement model that is either a `ReversibleModel` or a `LinearModel`.
This model will be particularly useful in the following example:
The sensor is located at [0, 0]. 
A target is located at [0, 1000]. This corresponds to a bearing-range measurement of [pi/2, 1000]. 
A clutter detection has a measurement of [0, 1000] (x, y = [1000, 0]). 
The `Euclidean` distance in measurement state space between the target and the clutter measurement is only 1.57 (pi/2). Unless the gate size is small, this would pass a …

Added TrackingStateSpaceDistanceGater

---

stonesoup/types/time.py

Hash functions were added to ``TimeRange`` and ``CompoundTimeRange``. The hash functions weren't inherrited from ``Interval``/s (See reason below). Some type annotation was also added.
From Python docs: A class that overrides [__eq__()](https://docs.python.org/3/reference/datamodel.html#object.__eq__) and does not define [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) will have its [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) implicitly set to None.

Added Hash Functions to `TimeRange` and `CompoundTimeRange`

---

stonesoup/updater/particle.py

This was using the prior particles, before resampling.

Fix issue with using un-resampled prior in regulariser

---

docs/examples/example_oosm_algorithm.py

Thir PR adds an example that shows how to implement Algorithm C [1, 2] to deal with out of sequence measurements. 
As other examples (see PR #939 and PR #915 ) we explain how to treat OOSM, in this specific case we employ a time-inverse dynamics method to create pseudo-measurements at "correct timestamp" from the delayed detections.
[1]  Y. Bar-Shalom, M. Mallick, H. Chen, R. Washburn, 2002, One-step solution for the general out-of-sequence measurement  problem in tracking, Proceedings of the 2002 IEEE Aerospace Conference.
[2] S. R. Maskell, R. G. Everitt, R. Wright, M. Briers, 2005, Multi-target out-of-sequence data association: Tracking using graphical models, Information Fusion.

Adding an example showing inverse-time dynamics method to deal with OOSM 

---

docs/examples/example_simple_oosm.py

This PR adds an example that shows how to use Algorithm A [1] to deal with Out of sequence measurements (OOSM). 
This example together with other PRs  (#915) aims to explain various techniques to deal with OOSM, in this case we consider a buffer of measurements and we re-order them to fix for any delay in their arrival. 
[1]  Y. Bar-Shalom, M. Mallick, H. Chen, R. Washburn, 2002, One-step solution for the general out-of-sequence measurement problem in tracking, Proceedings of the 2002 IEEE Aerospace Conference.

Adding an example showing how to deal with OOSM using a buffer of measurements

---

stonesoup/plotter.py

`MetricPlotter` had a hardcoded list of plottable metrics meaning every new plottable metric would require an update to the `plottable_metric` list in `MetricPlotter`.
This change compiles a list of plottable metrics of metrics generated for all metrics that value is a list of `SingleTimeMetric`.

Remove hardcoded Metrics from MetricPlotter

---

docs/examples/Example_data_fusion_from_sensors.py

In this PR, we add an example where we perform a 1 to 1 comparison between Extended Kalman filter, Unscented Kalman Filter and Particle filter tracking performances with data coming from two separate sensors, simplistically assumed to have the same specifics, in a multi-target scenario.

Example of data measurement fusion from two sensors, performance comparison

---

docs/examples/track_fusion_example.py
stonesoup/feeder/track.py

This PR adds an example were we do tracking fusion using partial tracks obtained by different sensors and compares how an Extended Kalman filter results are similar or different to a Particle filter.
This PR also adds a solution to use `Tracks2GaussianDetectionFeeder` for Particle States (and not only Gaussian states) as discussed and solved in #854 
I will add further examples (or enhance this one) regarding track fusion when other algorithms are presented (Covariance inflation)

Adding an example comparing Particle filters and kalman filters using track fusion

---

stonesoup/functions/__init__.py
stonesoup/movable/movable.py
stonesoup/platform/tests/test_platform_simple.py
stonesoup/sensor/base.py
stonesoup/sensor/tests/test_sensor.py

Calculation of the net orientation of a PlatformMountable on a Platform looks incorrect for 3D cases. It adds the platform's (MovementController's) orientation to the sensor's rotation_offset. Think of a sensor oriented to the left when its platform pitches up: addition would orient the sensor up too, when it should just roll. Instead, this PR rotates a vector aligned to the x-axis by the platform's orientation and the sensor's rotation_offset. This requires rotations in order: x, y, z. The current functions.init.build_rotation_matrix() does it the other way round (as required for other use cases) so a new build_rotation_matrix_xyz() has been added. Tests have been updated to match: rotation instead of addition requires orientation about x and z to be within +/-pi and in y to be within …

Correct calculation of net orientation of PlatformMountables

---

stonesoup/tracker/base.py
stonesoup/tracker/pointprocess.py
stonesoup/tracker/simple.py
stonesoup/tracker/tests/test_base.py

All current trackers require a detection feeder. It can be useful to progress a tracker manually without a detection feeder (see Multi-Sensor Fusion: Covariance Intersection Using Tracks as Measurements example). 
All current trackers and start their `__next__` function with:
```
time, detections = next(self.detector_iter)
```
I've added an `update_tracker` function which takes the time and detections from the detection feeder as an input. With this being a separate function, you can access it directly and bypass the detection feeder which may be easier in instances.
This also fixes issue #883 
This is my fourth iteration of trying to get this right. See #742, #779 and #888 for previous implementations.

Progress Trackers Manually: Option E

---

stonesoup/functions/__init__.py
stonesoup/functions/tests/test_functions.py

In cases where linalg error is produced, fall back to `cholesky_eps` designed for nearly positive-definite matrix, producing a user warning when this occurs.

Handle linalg error in gauss2sigma with Cholesky decomposition

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

Add method to select specific items to be shown
Add default argument to hide_plot_traces method to hide all traces if no labels are given

Add show_plot_traces method to plotly

---

docs/source/stonesoup.updater.rst
stonesoup/updater/probability.py
stonesoup/updater/tests/test_probability.py

Provides an updater based on probabilistic data association. See the documentation in the _Updaters_ section, or have a look at this gist: https://gist.github.com/jmbarr/92dc83e28c04026136d4f8706a1159c1

PDA Updater

---

stonesoup/functions/__init__.py
stonesoup/functions/tests/test_functions.py
stonesoup/predictor/kalman.py
stonesoup/predictor/tests/test_kalman.py
stonesoup/updater/kalman.py
stonesoup/updater/tests/test_kalman.py

Provides a cubature Kalman predictor and updater. (Credit should go to Bethany? I think.) 
Side issue is that there's some odd behaviour at certain configurations. I'll provide a gist to highlight that.

Cubature Kalman Filter

---

stonesoup/models/transition/base.py
stonesoup/models/transition/tests/test_combined.py

Add type checking for model_list in CombinedGaussianTransitionModel

---

stonesoup/metricgenerator/tracktotruthmetrics.py

The SIAP Rate of Track Number Change is the average rate of track number changes for true objects held by the metric manager defined on $(0, \infty]$. 
$$\frac{\sum_{truth=0}^{max(truths)} min(\mathrm{tracks\ needed\ to\ track\ } (truth)) - 1}{\sum_{truth=0}^{max(truths)}(\mathrm{total\ time\ tracked}(truth))}$$
Currently, this rate can be negative when the numerator function "min number tracks needed to track truth" is 0.
This fix excludes cases where the minimum number of tracks is zero from the numerator sum.

Use walrus operator to omit cases where no tracks exist in associations

---

stonesoup/updater/kalman.py
stonesoup/updater/recursive.py
stonesoup/updater/tests/test_kalman.py

Add the implementation of Joseph form of covariance to the Kalman Updater (as implemented in the Bayesian Recursive Updater).
Fix error arising when using Joseph form of covariance in BRUF with no measurement model.
Add tests.

Add Joseph form of covariance calculation to Kalman Updater

---

stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py

Fix `CartesianToElevationBearingRangeRate.inverse_function`. 
Current tests didn't find the problem as the state to measure was on the x-axis (`phi == theta == 0`).
New tests have been added which will fail on the old implementation.

Fix Inverse Function in CartesianToElevationBearingRangeRate

---

stonesoup/platform/base.py
stonesoup/platform/tests/test_platform_base.py

Added `Platform.id` property.
Added `Platform.ground_truth_path` that creates a GroundTruthPath from the Platform.
Added tests for the new functionality.

Added id property to Platform & property to create a GroundTruthPath from a Platform

---

.github/workflows/docs-link.yml

Skip CI for now, as won't run until merged.

Update docs link action to new name

---

stonesoup/dataassociator/probability.py
stonesoup/dataassociator/tests/test_probability.py

This pull request is the LBP algorithm of Williams and Lau (2014). This is an efficient mechanism for calculating the marginal association probabilities when performing soft data association (e.g. as in the JPDA filter).

Implementation of Loopy Belief Propagation (LBP)

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

This PR adds the ability to use the `MultiMeasurementInitiator` with the `GaussianMixtureInitiator`. Previously, the `GaussianMixtureInitiator` would only modify the last state of a `Track` so when a track with more than one state (from the `MultiMeasurementInitiator`) is presented, the result is a `Track` with a mixed set of states (`GaussianState` and `GaussianMixture`).

Fix GaussianMixtureInitiator to use a MultiMeasurementInitiator

---

docs/examples/sensormanagement/Autonomous_Source_Term_Estimation.py
docs/examples/sensormanagement/Monte_Carlo_Tree_Search_for_Autonomous_Source_Term_Estimation.py
docs/source/stonesoup.sensormanager.rst
stonesoup/models/measurement/gas.py
stonesoup/sensormanager/reward.py
stonesoup/sensormanager/tests/test_sensormanager.py
stonesoup/sensormanager/tree_search.py
stonesoup/types/state.py

This pull request introduces two new sensor management techniques to Stone Soup: `MonteCarloTreeSearchSensorManager` and `MCTSRolloutSensorManager`. These two managers are implementations of Monte Carlo tree search (MCTS) that construct a search tree based on actions and estimated future target states and estimate the action value resulting from this. Introducing these managers has also required a modification to reward functions that are to be compatible with MCTS. The `ExpectedKLDivergence` has been modified to include an extra property called `return_tracks` that allows the predicted tracks that have been used to calculate the KLD value to be returned to the invoking sensor manager so that it can be stored, in the case of MCTS, in the search tree. `ExpectedKLDivergence` is currently …

Monte Carlo Tree Search Sensor Manager and Autonomous STE Examples

---

docs/examples/sensormanagement/Monte_Carlo_Tree_Search_for_Autonomous_Source_Term_Estimation.py
stonesoup/sensormanager/reward.py
stonesoup/sensormanager/tests/test_sensormanager.py

This PR introduces several minor updates, mainly to the `UncertaintyRewardFunction`. The first change is to add `return_tracks` as a property to the `UncertaintyRewardFunction`  allowing it to be used with the MCTS type sensor managers and any other sensor management algorithm that requires storage and reuse of states estimated during reward calculation. A test has also been added to verify this functionality with MCTS.
The second change to `UncertaintyRewardFunction` is in generating detections from predicted future target states. As the `measure` method of a sensor is not designed to operate on particle states, it will return a measurement for every `state_vector` in `state_vectors` of the `ParticleState` which is not handled by a `ParticleUpdater` under usual circumstances. To prevent …

Update UncertaintyRewardFunction to return tracks and minor modifications

---

docs/examples/dataassociation/mht_example.py
docs/examples/mht_example.py

This PR adds an example of a Multi-Hypothesis tracking using the Multi-frame assignment components. 
This example was supposed to rely more on Stone Soup components (e.g., `GaussianMixtureInitiator` and `MultiTargetTracker`), however the current implementation of such components is not aligned with the MFA components making complex to deal with it (e.g. #896).
This example shows how to set up this type of simulations in a more general way than the [example present](https://stonesoup.readthedocs.io/en/v1.1/auto_examples/MFA_example.html#sphx-glr-auto-examples-mfa-example-py>) in the documentation.

Adding an example showing an explicit MHT application using MFA components

---

docs/examples/extended_object_tracking_example.py

This PR adds an example showing how to use Stone Soup components for a multi target extended object tracking scenario.
This example assumes that multiple detections are generated by each target at each timestep, by randomly drawing samples from an extended shape (ellipse in this case) and then employs a clustering algorithm to process the multiple detections and generate a new set of detections for performing the tracking duties.

Adding an example of extended object tracking (EOT)

---

docs/examples/readers/Custom_Pandas_Dataloader.py
stonesoup/measures/state.py
stonesoup/movable/movable.py
stonesoup/reader/aishub.py
stonesoup/reader/generic.py
stonesoup/reader/hdf5.py
stonesoup/reader/kafka.py
stonesoup/reader/opensky.py
stonesoup/reader/pandas_reader.py
stonesoup/tests/test_stitcher.py
stonesoup/types/array.py

- [Fix deprecated array wrap method without context/return_scalar](https://github.com/dstl/Stone-Soup/commit/84fb7ad645b8aa62273d3593d36b6bbffcc2ea40)
- [Fix deprecated utcfromtimestamp](https://github.com/dstl/Stone-Soup/commit/f5045a1f2369bfe3c24083512410f17f31dfe873)
- [Fix deprecation warnings for ndim > 0 arrays becoming scalar](https://github.com/dstl/Stone-Soup/commit/608446f1516caf4013ba487bb9c65e54bcda4474)
- [Fix deprecated utcnow](https://github.com/dstl/Stone-Soup/pull/1045/commits/c6503fef0258e4d135983e08dafc7ef4de6ebe50)

Minor deprecation fixes

---

stonesoup/base.py

Add new argument for fillvalue and indent that cause error if missing in some cases
Primarily errors were with indent that was introduced in Python 3.12

Fix repr on Base class

---

stonesoup/types/particle.py
stonesoup/types/state.py
stonesoup/types/tests/test_particle.py
stonesoup/types/tests/test_state.py

This allows references to be kept where parent parent remains in memory elsewhere, like track history.
This covers additional cases from changes in #1023

Set weakref to particle parent parent, rather than None

---

stonesoup/metricgenerator/ospametric.py

In case where there are multiple estimates for timestamp on a track (e.g. multi-sensor fusion), metric should only really be calculated using last state added at that timestamp.

Only use one track state per timestamp in (G)OSPA metric

---

stonesoup/metricgenerator/ospametric.py
stonesoup/metricgenerator/tests/test_ospametric.py

`GOSPAMetric.compute_over_time()` was taking a complete copy of _all_ measurements and ground truth states for every timestep in the sequence. Additionally, it used multiple full linear masks for every iteration on the sorted timestamps. These steps cause the metric to have $` \mathcal{O}(n^2) `$ running time in the number of timesteps, resulting in slow compute on long datasets.
This PR performs the copying once and uses `itertools.groupby()` to avoid the linear masking in each iteration. As a result, `GOSPAMetric` now uses slightly less memory (we perform the same copy, but save the masking) and, in practice, runs linearly in the number of timesteps. The PR also includes a test which demonstrates 30-40x speedup on a 1k timestep long sequence. Offline I'm seeing 150x speedup (going from …

GOSPAMetric: Avoid unnecessary copies and inefficient masking

---

stonesoup/sensormanager/reward.py

This pull request addresses an issue when constructing `GroundTruthState` for generating detections in the `UncertaintyReward` class that was adversely affecting sensor management performance when using this reward. There are a number of reasons for these changes:
1. Fix the issue where the `detections` dict would be populated with repeated detections of one track instead of each detectable track, causing the sensor manager to only focus on one track in sensor management for multiple tracks.
2. Pass all tracks as `GroundTruthState` into `sensor.measure` such that sensor specific behaviours when detecting multiple targets can be maintained in sensor management.
3. Create a mapping from `GroundTruthState` to `predicted_track` such that the prediction object can be passed to the updater …

Fix UncertaintyReward bug and improve ExpectedKLDivergence

---

stonesoup/dataassociator/tracktotrack.py

In edge case where distance was exactly zero, `min_dist` would evaluate false.

Handle distance of 0 correctly in TrackToTruth associator

---

docs/examples/dataassociation/Comparing_EHM_JPDA_example.py
docs/examples/dataassociation/One_to_One_Associator.py
docs/examples/dataassociation/mht_example.py
docs/examples/eot/extended_object_tracking_example.py
docs/examples/filters/Multi_Tracker_Example.py
docs/examples/filters/bearing_only_example.py
docs/examples/oosm/KalmanFilterOOSMExample.py
docs/examples/oosm/PF_OOSM_example.py
docs/examples/oosm/example_oosm_algorithm.py
docs/examples/oosm/example_simple_oosm.py
docs/examples/plotting/Polar_Plotting.py
docs/examples/sensorfusion/Example_data_fusion_from_sensors.py
docs/examples/trackfusion/Track2Track_Fusion_Example.py
docs/examples/trackfusion/track_fusion_example.py
docs/tutorials/filters/AKKF.py
docs/tutorials/filters/ASDFilter.py
stonesoup/plotter.py
stonesoup/tests/test_plotter.py

This simplifies using the plot_### functions. To avoid breaking changes, the individual labels (e.g. 'truths_label') can still be used. 
For some plotters the measurement legend would add 'clutter' or 'detections' to end of the measure label. For other plotters it wouldn't.

Update Plotter Labels

---

stonesoup/predictor/asd.py

When using ASD with out of sequence measurements, the covariance prior to OOSM measurement would go negative. Through testing, it's highlighted that setting the correlation matrices predicted covariance to that one based on original posterior (i.e. approx value it would have been set to if measurement was received in sequence) seems to resolve the issue.

Fix ASD with OOSM

---

stonesoup/base.py
stonesoup/dataassociator/tests/test_tracktotrack.py
stonesoup/dataassociator/tracktotrack.py
stonesoup/functions/interpolate.py
stonesoup/functions/tests/test_interpolate.py
stonesoup/measures/state.py

- Alter `interpolate_state_mutable_sequence` to use the previous state as a template for the new interpolated state instead of a new `State` object
- Add more explanation to `TypeError`s in `Base`
- Fixed edge case bug in `TrackToTruth` when empty tracks or truths cause an exception to be raised. A test has also been added

Minor Improvements August 24

---

stonesoup/types/state.py

As presented and discussed in #1081 , the mean and covar evaluation of particle state was not stable enough for edge cases. This PR proposes a solution for that.

Upgrade: more stable mean and covar evaluation of particle state update

---

stonesoup/metricgenerator/base.py
stonesoup/metricgenerator/clearmotmetrics.py
stonesoup/metricgenerator/manager.py
stonesoup/metricgenerator/metrictables.py
stonesoup/types/tests/test_metric.py

While working on a metrics example (upcoming PR ...) with `ClearMotMetrics` and `MultiManager`, I recognized that the latter [expects](https://github.com/kopytjuk/Stone-Soup/blob/0b649df4b78b5059794e072579e670013ac4af98/stonesoup/metricgenerator/manager.py#L93) passed metric generators to have a `generator_name` property, which the `ClearMotMetrics` did not have.
Thus, I added the following:
- Added `generator_name` abstract property to `MultiManager` to make it clear for future developers to follow this protocol
- Added `generator_name` property to `ClearMotMetrics`

Extend `MetricGenerator` interface with `generator_name` and add  it to `ClearMotMetrics`

---

stonesoup/functions/__init__.py
stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py
stonesoup/sensor/sensor.py

These changes speed up some sensor management examples around x3
- Add caching for rotation matrix functions
- Pass `measurement_model` to `is_detectable` in `SimpleSensor`
This includes a breaking change, where anything sub classing from `SimpleSensor` will need to add `measurement_model` argument to `is_detectable` method (even if not using it).

Sensor performance improvement

---

stonesoup/hypothesiser/distance.py
stonesoup/hypothesiser/tests/test_distance.py
stonesoup/proposal/base.py
stonesoup/proposal/simple.py

Change in #1080 causes the hypothesiser not able to take advantage of caching, causing docs builds to fail.
Not sure this is the best fix, but I'll propose it for now, but may need more thought.

Make passing measurements in distance hypothesiser optional

---

stonesoup/functions/__init__.py
stonesoup/metricgenerator/tests/test_ospametric.py
stonesoup/models/measurement/gas.py
stonesoup/models/measurement/tests/test_gas.py
stonesoup/predictor/particle.py
stonesoup/predictor/tests/test_particle.py
stonesoup/sampler/detection.py
stonesoup/sampler/particle.py
stonesoup/sensor/tests/test_gas.py
stonesoup/tests/test_kernel.py
stonesoup/tests/test_stitcher.py
stonesoup/types/tests/test_prediction.py
stonesoup/types/tests/test_update.py

This removes all cases where the NumPy global seed is set in tests, such that setting of seed in one test doesn't impact others.
This also makes some minor changes in samplers to optionally use a provided seed, and fallback to global if not provided (similar to models).

Don't set global random seed in tests

---

stonesoup/proposal/__init__.py

A missing `__init__` file in the proposal class created a problem when calling stonesoup as a module. 
Spotted by @sglvladi

Add init file for proposal class

---

stonesoup/functions/__init__.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py

This provides a notable improvement in calculating logpdf, by carrying out mod_bearing or mod_elevation in vectorised way on float arrays.
This change only impacts internal calculations, so public methods still return custom typed arrays as before.
This also removed a bunch of redundant and incorrect doc strings (reference to time interval)

Vectorise logpdf mod_angle calculations in angle based models

---

docs/examples/metrics/CLEAR_MOT.py

Since the calculation of CLEAR MOT metrics requires its own  `ClearMotAssociator`, I think it would be helpful to have an end-to-end example together with `MultiManager` where users just can copy&paste from. 
I built up on top of `06_DataAssociation-MultiTargetTutorial.py` tutorial to generate truths and tracks.
Since I am not a native speaker, feel free to correct my grammar and choice of words!
CC to @sdhiscocks, since he reviewed the other 3 PRs around CLEAR MOT.

Add CLEAR MOT example

---

stonesoup/updater/pointprocess.py

I believe I noticed a small error in your PointProcessUpdater component regarding the use of the survival probability term
Point 1 (line 78) To be fully consistent with Mr. Vo's pseudocode, it is necessary to discriminate between new and existing targets when applying survival probability. Indeed, only the weight of existing targets should be multiplied by the survival probability. Therefore, it seems that a test is missing at this point. It should be noted that this is not a critical issue, as it only results in a different weighting for the components related to spontaneous births.
Point 2 (line 108): added "* self.prob_survival".
When you process the "missed_detection" hypotheses, it seems that the survival probability is not taken into account (note: the correction term l1 is always …

Small error PointProcessUpdater regarding the use of the survival probability term

---

docs/examples/sensormanagement/Monte_Carlo_Tree_Search_for_Autonomous_Source_Term_Estimation.py
stonesoup/sensormanager/tests/test_sensormanager.py
stonesoup/sensormanager/tree_search.py

This pull request modifies the action value calculation for Monte Carlo tree search. The fix is most relevant for `MCTSRolloutSensorManager` and introduces a maximum search depth class property that specifies the maximum number of time steps into the future that the algorithm can search to, and ensures that all policy rollouts run to this time step, rather than ensuring that rollouts are run for the same duration. The action value is cumulatively calculated as the sum of all simulation results, recalling previously estimated reward values at existing nodes in the search tree. This fix will correct the over exploratory nature of the algorithm that was happening before the fix.
The MCTS sensor management example has been modified to use the `search_depth` rather than `rollout_depth` to …

Monte Carlo Tree Search action value correction

---

stonesoup/movable/tests/test_movable.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py

Thank you for nice software.
In this PR, I fixed StateMutableSequence so that its subclasses can have mandatory properties. Indeed, if a subclass has a mandatory property, the subclass cannot be instantiated, or its mandatory property will be unexpectedly put in a list, depending on how arguments are passed to the constructor (see the changes in `stonesoup/types/tests/test_state.py`). A simple fix can resolve this issue.
There is one side effect that affects the error raised by `MovingMovable` when it is instantiated without specifying the mandatory argument "states". This change has made a test for MovingMovable fail, although I think for most users, the change itself is harmless. Therefore, I fix the test to make it pass.

Fix StateMutableSequence to allow for subclasses with mandatory properties

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

Add animated plotter class for polar plotting based on the AnimatedPlotterly Code

Add AnimatedPolarPlotterly Class

---

stonesoup/types/prediction.py
stonesoup/types/tests/test_prediction.py

This changes behaviour to rather than copying priors and setting prior to None, to instead use weak references. This means objects stay the same, while still allowing objects to clear memory if no longer maintained in a Track for example.
This is similar implementation as use of ParticleState parents.

Use weakref for prior priors

---

stonesoup/plotter.py

I often find that the track uncertainties overlap too much and result in a solid block of color obscuring the rest of the plot. This allows the user to decrease the alpha to prevent this.

Make track uncertainty alpha an optional keyword argument

---

.circleci/config.yml
pyproject.toml
stonesoup/sensormanager/action.py
stonesoup/sensormanager/optuna.py
stonesoup/sensormanager/tests/test_optuna.py

Add a new sensor manager that utilises the `optuna` module to determine the best action available within a given ``timeout`` period.

Add Optuna Sensor Manager

---

stonesoup/smoother/kalman.py

This allows types checks for types which may be registered Gaussian States but don't follow the particular Prediction/Update lineage.

Kalman Smoother check GaussianState and Prediction/Update separately

---

.circleci/config.yml

This is follow on from #1092, where a subset of dependencies were used for Python 3.13 as some libraries weren't available for 3.13 at that time.

Use full test template for Python 3.13 CircleCI config

---

stonesoup/updater/probability.py
stonesoup/updater/tests/test_probability.py

This is generally useful where looking to use this method, but can't easily pass arguments into updater.
Also remove some unneeded work around code.

Allow setting of gm_method at instance level for PDAUpdater

---

stonesoup/predictor/particle.py
stonesoup/proposal/simple.py
stonesoup/proposal/tests/test_simple.py

This PR renames the proposals introduced in #1080 to make them more intuitive and representative of their purpose. Specifically:
- `PriorAsProposal` has been renamed to `DynamicsProposal`
- `KFasProposal` has been renamed to `KalmanProposal`.
This is also an attempt to make the names of the classes consistent with the names that will be used in the paper we aim to publish to Fusion 2025.
**Note**: This PR introduces breaking changes for code that references the proposals directly. Any legacy code, or more generally code that does not explicitly specify a proposal, should run without errors.

Rename PriorAsProposal to DynamicsProposal, and KFasProposal to KalmanProposal

---

stonesoup/models/measurement/nonlinear.py

Handle 9D state in CartesianToElevationBearingRangeRate 

---

stonesoup/feeder/multi.py
stonesoup/feeder/tests/test_multi.py

These multi data feeders are designed to allow reading from real-time data sources, where there may be latencies or data coming out of sequence. This includes the standard FIFO, LIFO and Priorty Queue classes from Python standard library, as well as a custom prioity queue which drops old data, rather than blocking or raising error when full.

Add multi data feeders with queues

---

stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_ct.py

Both dimensions were using the same (first dimension's) noise parameter.

Fix KnownTurnRate model not using 2nd noise parameter

---

stonesoup/models/transition/linear.py
stonesoup/models/transition/nonlinear.py
stonesoup/models/transition/tests/conftest.py
stonesoup/models/transition/tests/test_ca.py
stonesoup/models/transition/tests/test_combined.py
stonesoup/models/transition/tests/test_ct.py
stonesoup/models/transition/tests/test_cts.py
stonesoup/models/transition/tests/test_cv.py
stonesoup/models/transition/tests/test_nlct.py
stonesoup/models/transition/tests/test_nlcts.py
stonesoup/models/transition/tests/test_ou.py
stonesoup/models/transition/tests/test_rw.py
stonesoup/models/transition/tests/test_singer.py
stonesoup/models/transition/tests/test_singer_approximate.py

Models are updated to allow backwards prediction, which can be useful for dealing with track stitching, out of sequence measurements, etc.
In general many models supported this in their function, but not for covariance.

Update transition models to support backward prediction

---

stonesoup/sensor/radar/tests/test_radar.py
stonesoup/sensormanager/action.py

Positions of targets in the Rotating EBR sensor test were placed in the wrong position previously and so the tests only passed due to the sensor's FOV not being small enough.
Targets have been moved to the correct positions and the FOV's have been reduced.
The argument `value` has been added to the abstractmethod of `action_from_value` in the `RealNumberActionGenerator`.

Fix tests for RadarRotatingElevationBearingRange sensor

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

Addresses #1145 
This PR updates the `plot_measurements(...)` method for all plotters/plotterlys. The method has a new optional parameter `show_clutter` (default `True`). The use case is to simplify plotting measurements in scenarios with a high clutter to truth ratio, where the user may want to sometimes make plots without the clutter points (which would obscure the rest of the data, for example).
I also added some unit tests for the new functionality, keeping all existing tests as they were.
Please let me know what you think!

Make Clutter From Measurement Plotter More Configurable

---

docs/examples/filters/Multi_Tracker_Example.py
docs/examples/metrics/Metrics.py
docs/examples/readers/Custom_Pandas_Dataloader.py
docs/source/conf.py
docs/source/contributing.rst
docs/source/stonesoup.reader.rst
stonesoup/reader/pandas_reader.py

Addresses #1146 
The main purpose of this PR is to clarify the Pandas DataFrame support in Stone Soup:
1. Mention the example is only for demonstration purposes (the support for reading pandas DFs is already included in Stone Soup). I was originally going to remove the `Reader` implementations from that example. But then I found #354 and #707 about it serving as a demonstration for how users can add custom Reader classes and figured it is worth keeping, along with a clarifying note.
2. Make the Pandas DataFrame Reader classes appear in the Stone Soup docs.
Along the way I found a few other tweaks to examples and documentation that seem like improvements (happy to discuss).
I also updated a few URLs in the sphinx document generation because the command output suggested to do so.

Updated the Pandas DataFrame Example and a few other small tweaks

---

stonesoup/platform/__init__.py
stonesoup/platform/base.py
stonesoup/platform/tests/test_platform_base.py

This PR adds a `PathBasedPlatform` class. This class has the abiltiy to define a platform by a `GroundTruthPath` rather than a an individual `TransitionModel` or multiple.

Add PathBasedPlatform

---

stonesoup/sensor/radar/radar.py

RadarRotatingElevationBearingRange sensor currently uses self.measurement_model regardless of the measurement_model argument given, this PR fixes that.

Use measuremenet_model argument in RotatingElevationBearingRange sensor

---

docs/ci-requirements.txt
docs/examples/simulation/ODE_example.py
pyproject.toml

This PR follows the (now closed #952) where I changed the example from a space domain case to a navigation like transition model (constant heading). 
The example provides a snapshot on how to linearise a non-linear time variant transition model using the Van Loan method. 
Some feedback on the document provided in the previous PR are incomporated already. 
The example considered mimics the one presented in the following paper: 
[1] Kountouriotis, Panagiotis-Aristidis, and Simon Maskell. "Maneuvering target tracking using an unbiased nearly constant heading model." 2012 15th International Conference on Information Fusion. IEEE, 2012. 
(https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6290578.)

New example that shows linearised ODE as transition model

---

stonesoup/smoother/kalman.py
stonesoup/types/tests/test_track.py
stonesoup/types/track.py

Shallow copy track in smoothers

---

stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py

The RadarBearingRangeRate2D sensor and associated CartesianToBearingRangeRate2D measurement model were created to support tracking from measurements of bearing, range, and range rate to a 4D state space [x, vx, y, vy]. The current RadarBearingRangeRate/CartesianToBearingRangeRate class only supports a 6D state vector [x, vx, y, vy, z, vz] as a requirement for the creation of the rotation matrix.
Additionally, both measurement models were given inverse functions to support plotting measurements to a Cartesian plot space.

Added support for a 4D state vector when using a range, bearing, range rate radar model

---

stonesoup/movable/movable.py
stonesoup/platform/tests/test_platform_base.py

Slight change to how orientation is calculated for moving platforms. Where the velocity of the platform is small, the orientation is calculated based on the direction it travelled from its previous position. Where the platform has only moved a small distance, and for a non-moving platform the orientation from the previous time step is used.

Platform orientation calculated from previous velocity

---

docs/source/stonesoup.movable.rst
stonesoup/movable/action/__init__.py
stonesoup/movable/action/move_position_action.py
stonesoup/movable/action/tests/test_move_position_action.py
stonesoup/movable/sample.py

This PR introduces additional `movable` components for actionable platforms. New sample based category of `movable` and action generator have been introduced: `_SampleActionableMovable` and `SamplePositionActionGenerator`, along with an implementation based on uniform sampling within a circle around the current platform position.
`CircleSamplePositionActionGenerator` implements the generator logic behind the contribution, yielding `MovePositionAction`s based on sampling from a circle around the current position. Radius of the circle is defined by the user with the property: `maximum_travel`. The user can also specify the number of samples to generate with `n_samples`. This generator is implemented with `CircleSampleActionableMovable` and inherits its base methods from …

Sample Position Action Generator and Movable

---

stonesoup/metricgenerator/ospametric.py

This allows support of datetimes with timezone, which currently raises a warning in NumPy but in future will error.

Use native Python datetime objects in GOSPA metric

---

stonesoup/movable/action/move_position_action.py
stonesoup/movable/action/tests/test_move_position_action.py

The `CircleSamplePositionActionGenerator` only generates actions in a 2D space.
This PR uses the `action_mapping` property of the generator to allow the handling of states that have more than 2 positional components.
This makes it so that actions in x and y can be generated for a x, y and z state where previously an error would have occurred.

Use `action_mapping` property to use the `CircleSamplePositionActionGenerator` in a 3D space

---

.circleci/config.yml
.readthedocs.yml
docs/ci-requirements.txt
stonesoup/plotter.py

Due to changes with Kaleido, Chrome must be manually downloaded if not already installed (the case on CI/CD set up).
Also, new version doesn't like custom Bearing/Elevation types, so force these to floats (already done for tracks/measurements but not for truth).

Fix issue with docs building with new kaleido release

---

stonesoup/plotter.py

Noticed a typo where the `Track` type wasn't linked in `AnimatedPlotterly`'s `plot_tracks` docstring. 
Built the html files to verify that these changed linked it correctly. 
This is my first ever PR so let me know if I messed anything up :).

Fixed typo in Animated Plotterly plot_tracks docstring

---

stonesoup/hypothesiser/probability.py
stonesoup/hypothesiser/tests/test_probability.py

Default `True` for current behaviour, but allow setting to `False` for cases where normalisation isn't wanted, e.g. MHT based tracker

Add normalise option to PDA Hypothesiser
