README.md

Issue 106. Add link to original article

---

stonesoup/reader/generic.py
stonesoup/reader/tests/test_generic.py

Needed to add support for tsv formats etc.

Expand csv reader

---

stonesoup/base.py
stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_ca.py
stonesoup/tests/test_declarative.py

This model keeps the Nth derivative with respect to time constant.
Also packaged `ConstantVelocity` and `ConstantAcceleration` as variants with N=1 and N=2.

Nth Derivative model

---

stonesoup/buffered_generator.py
stonesoup/reader/aishub.py
stonesoup/reader/base.py
stonesoup/reader/generic.py
stonesoup/reader/tests/test_aishub.py
stonesoup/reader/tests/test_generic.py
stonesoup/simulator/base.py
stonesoup/simulator/simple.py
stonesoup/simulator/tests/test_detections.py
stonesoup/simulator/tests/test_groundtruth.py
stonesoup/tests/test_buffered_generator.py
stonesoup/tracker/base.py
stonesoup/tracker/simple.py
stonesoup/tracker/tests/test_simple.py

Creates a new BufferedGenerator class for objects like Trackers, Readers etc. 
Converts them into actual generators with the original generator method still available for backwards compatibility. This means that (for example) CSVDetectionReader now behaves the same as python's csv readers, making code more pythonic overall. 
The current state of each generator is available from 'generator_object.current'.

Buffered generator

---

stonesoup/reader/generic.py
stonesoup/reader/tests/test_generic.py

Created a new CSV reader specifically for reading ground truth data, and generating ground truth paths. Takes in a .csv file (and relevant field name data), and returns a series of ground truth paths.

Ground truth reader

---

stonesoup/models/base.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/sensor/radar.py

Changed the method names as per discussion with Steve about their logical meaning.
Also added an inverse function to convert range/bearing co-ordinates to Cartesian, using Jacobian matrices.

Add inverse bearing function &reverse method names

---

stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_ou.py
stonesoup/models/transition/tests/test_rw.py
stonesoup/models/transition/tests/test_singer.py
stonesoup/models/transition/tests/test_singer_approximate.py

Adds the Nth derivative decay model, and packages the OU and singer in to that.

Nth Derivative Decay

---

stonesoup/models/transition/linear.py

Changes specifying which models are discrete or continuous. At time of commit, all are discrete (I think).

Adds some documentation

---

stonesoup/buffered_generator.py
stonesoup/feeder/filter.py
stonesoup/feeder/geo.py
stonesoup/feeder/tests/conftest.py
stonesoup/feeder/tests/test_filter.py
stonesoup/feeder/tests/test_geo.py
stonesoup/feeder/tests/test_time.py
stonesoup/feeder/time.py
stonesoup/reader/base.py
stonesoup/reader/generic.py
stonesoup/reader/tests/test_generic.py
stonesoup/reader/tests/test_yaml.py
stonesoup/reader/yaml.py
stonesoup/simulator/simple.py
stonesoup/tracker/base.py
stonesoup/tracker/simple.py
stonesoup/tracker/tests/conftest.py
stonesoup/writer/tests/conftest.py
stonesoup/writer/yaml.py

Also includes some changes to buffered generator class to resolve some issues.

Update components to use buffered generator

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

Altered the linear initiator to incorporate non-linear co-ordinates and changed name to simple. Added multi measurement initiator. Altered test file to test new parts.

add multi meas initiator & non linear w tests

---

docs/source/stonesoup.sensor.rst
stonesoup/platform/simple.py
stonesoup/sensor/base.py
stonesoup/sensor/passive.py
stonesoup/sensor/radar.py
stonesoup/sensor/tests/test_passive.py
stonesoup/sensor/tests/test_radar.py

Adds a bearings only sensor class which will be required in order to undertake bearings only tracking.

Passive sensor

---

docs/source/conf.py
stonesoup/models/measurement/linear.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_ca.py
stonesoup/models/transition/tests/test_ct.py
stonesoup/models/transition/tests/test_cv.py
stonesoup/models/transition/tests/test_ou.py
stonesoup/models/transition/tests/test_rw.py
stonesoup/models/transition/tests/test_singer.py
stonesoup/models/transition/tests/test_singer_approximate.py
stonesoup/tests/conftest.py

Fix a number of deprecated warnings.

Fix deprecated warning for pytest, Sphinx and SciPy

---

stonesoup/models/base.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_combined.py
stonesoup/models/measurement/tests/test_models.py

This allows multiple measurement models to be combined together, in particular for combining a non-linear model with one or more, linear or non-linear models.

Add a combined non-linear Gaussian measurement model 

---

stonesoup/simulator/tests/test_detections.py

Resolve issue with simulator tests sometimes failing

---

stonesoup/platform/tests/test_platform_simple.py
stonesoup/sensor/base.py

A couple of small bug fixes: 
1. Fix the signature of `Sensor.measure()` so that it includes self as the first argument.
2. Fix the `test_3d_platform` so that it actually tests what it was supposed to. Due to a typo it was previously only testing the last element of the vector rather than the whole vector. I also needed to fix the test case data so that the tests pass. I suspect a copy/paste error had occurred.

Fix platform tests

---

stonesoup/sensor/radar/radar.py
tox.ini

This PR addresses  #161. I appreciate that it has not been discussed at length and agreed, but this shows how it could be done (and will check that CircleCI honours the config). 
If people decide they are happy this can be pulled. If it gets objections, we can close this without pulling.

Increase allowed line length

---

stonesoup/dataassociator/tracktotrack.py
stonesoup/metricgenerator/ospametric.py
stonesoup/models/base.py
stonesoup/models/measurement/linear.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_combined.py
stonesoup/models/measurement/tests/test_lg.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/models/transition/tests/test_ca.py
stonesoup/models/transition/tests/test_ct.py
stonesoup/models/transition/tests/test_cv.py
stonesoup/models/transition/tests/test_ou.py
stonesoup/models/transition/tests/test_rw.py
stonesoup/models/transition/tests/test_singer.py
stonesoup/models/transition/tests/test_singer_approximate.py
stonesoup/platform/base.py
stonesoup/predictor/kalman.py
stonesoup/predictor/particle.py
stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py
stonesoup/sensor/tests/test_passive.py
stonesoup/simulator/simple.py
stonesoup/simulator/tests/conftest.py
stonesoup/updater/kalman.py
stonesoup/updater/particle.py

Previously, function methods had default noise set to None. In which case noise was added, leading to confusion.
Resolves: #149

Updated models so function does not add noise by default

---

docs/source/stonesoup.simulator.rst
stonesoup/platform/base.py
stonesoup/simulator/platform.py
stonesoup/simulator/tests/conftest.py
stonesoup/simulator/tests/test_platform.py

Previously, simulated detections were provided by measurement models, which did not result in an accurate representation of detection possibilities for each individual sensor/collection of sensors on a platform.
Resolves: #164

Added platform detection simulators.

---

docs/source/doc_extensions.py
stonesoup/platform/simple.py

Modification to doc_extensions to allow Sphinx to parse types in a declarative Property of the form List[object] or similar. 
Also made a single change to Platform to demonstrate the changes

Update doc extensions for richer type definitions

---

stonesoup/dataassociator/probability.py
stonesoup/dataassociator/tests/test_probability.py

This PR addresses #185 and removes unnecessary processing from ``SimplePDA``. Also, ``SimplePDA`` is renamed to ``PDA``.

Simplify SimplePDA

---

.circleci/config.yml
setup.py
stonesoup/astronomical_conversions.py
stonesoup/initiator/preliminaryorbitdetermination.py
stonesoup/initiator/tests/test_orbital.py
stonesoup/models/transition/orbital/__init__.py
stonesoup/models/transition/orbital/orbit.py
stonesoup/models/transition/orbital/tests/test_orbit.py
stonesoup/orbital_functions.py
stonesoup/types/orbitalstate.py

Provided initial implementation of sgp4 transition model + test

external sgp4 propagator into transition model

---

stonesoup/models/transition/linear.py
stonesoup/models/transition/tests/test_cts.py
stonesoup/models/transition/tests/test_ou.py
stonesoup/models/transition/tests/test_singer.py
stonesoup/models/transition/tests/test_singer_approximate.py

Adds a transition model which allows for a constant turn in 2 state variables which are not adjacent in the state vector, eg x and z in the (x, y, z) state vector

Constant turn sandwich

---

docs/source/stonesoup.deleter.rst
stonesoup/deleter/multi.py
stonesoup/deleter/tests/test_multi.py

The methods apply a list of deleters to input tracks

Added multi-deleter methods

---

stonesoup/platform/base.py
stonesoup/platform/tests/test_platform_base.py

The platform's movement behaviour is dictated by a list of transition models with corresponding transition durations.

Added MultiTransitionMovingPlatform class

---

stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py
stonesoup/platform/tests/test_platform_simple.py
stonesoup/sensor/base.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/radar/tests/test_radar.py
stonesoup/tests/test_functions.py

Extension to measurement models and radar sensors to provide a range rate measurement capability

Range rate radar extension

---

stonesoup/reader/generic.py
stonesoup/reader/tests/test_generic.py

- Modifications try to reuse code more now where possible
- Groundtruth now includes id
- Groundtruth and detctions that of the same timestamp are yielded together

Modify detection and ground truth CSV readers

---

.circleci/config.yml
.gitignore
.readthedocs.yml
docs/source/_static/css/custom.css
docs/source/conf.py
docs/source/doc_extensions.py
docs/source/index.rst
docs/tutorials/01_KalmanFilterTutorial.py
docs/tutorials/README.rst
setup.py
tox.ini

Work in progress to add tutorials to documentation using sphinx gallery.
Includes changes to build on CircleCI.
Note: Test failures due to FLAKE8 update.

Added sphinx-gallery in to documentation

---

stonesoup/models/measurement/nonlinear.py

Modification to doc strings to ensure correct generation in RangeRate methods.

Modify non-linear doc strings for Range Rate methods

---

stonesoup/feeder/base.py
stonesoup/feeder/filter.py
stonesoup/feeder/geo.py
stonesoup/feeder/multi.py
stonesoup/feeder/tests/conftest.py
stonesoup/feeder/tests/test_filter.py
stonesoup/feeder/tests/test_geo.py
stonesoup/feeder/tests/test_multi.py
stonesoup/feeder/tests/test_time.py
stonesoup/feeder/time.py

Modified wording and inheritance of feeders to allow for
ground truth path data to be fed in.

Allowed for generic data input to appropriate detection feeders

---

docs/tutorials/08_Initiators_&_Deleters.py
docs/tutorials/09_Initiators_&_Deleters.py

Tutorial for initiators and deleters.

Add Initiators & Deleters tutorial

---

docs/examples/Metrics.py
docs/examples/README.rst
docs/source/conf.py
docs/source/doc_extensions.py
docs/source/index.rst
stonesoup/dataassociator/tests/test_tracktotrack.py
stonesoup/dataassociator/tracktotrack.py
stonesoup/metricgenerator/manager.py
stonesoup/metricgenerator/metrictables.py
stonesoup/metricgenerator/ospametric.py
stonesoup/metricgenerator/plotter.py
stonesoup/metricgenerator/tests/test_basicmetrics.py
stonesoup/metricgenerator/tests/test_manager.py
stonesoup/metricgenerator/tests/test_ospametric.py
tox.ini

- Use Measures in track to track association and OSPA metrics.
- Metric generator now runs association if not done when computing metrics
- Updates to SIAP metric table 
- Add Metrics example, creating examples section
- Dynamically build legend for plot metric, and change plot order

Metrics example and changes

---

docs/tutorials/01_KalmanFilterTutorial.py
docs/tutorials/02_ExtendedKalmanFilterTutorial.py
docs/tutorials/03_UnscentedKalmanFilterTutorial.py
docs/tutorials/04_ParticleFilter.py
docs/tutorials/05_DataAssociation-Clutter.py
docs/tutorials/06_DataAssociation-MultiTargetTutorial.py
docs/tutorials/07_PDATutorial.py
docs/tutorials/08_JPDATutorial.py
docs/tutorials/09_Initiators_&_Deleters.py

Added some key learning points at the end, and the ability to set a random seed.

Tweaks to the single target tutorials. 

---

docs/examples/Sensor_Platform_Simulation.py

Documents example of a single sensor platform being deployed within a simulator

Single sensor platform example

---

docs/examples/Moving_Platform_Simulation.py
docs/source/conf.py
stonesoup/models/measurement/nonlinear.py

Multi-sensor platform simulation example

Multi-sensor platform Simulation Example

---

stonesoup/reader/tests/test_yaml.py
stonesoup/reader/yaml.py

This resolves issues when using paths/tracks in sets

Change YAMLReader to return same path/track, updating the states

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

Note: Unsure why it was not done this way beforehand.

Fix mapped dimensions in simple measurement initiator

---

stonesoup/measures.py
stonesoup/tests/test_measures.py

This PR fixes matrix multiplication in the Hellinger function, correct the equations in the documentation and updates the tests.

Fix Hellinger distance.

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

Needed exception for NotImplementedError on initiate method.

Add correct error for simple measurement initiator

---

stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tracktotruthmetrics.py

Fix divide by zero in SIAP Metrics when no truth/tracks

---

docs/examples/Metrics.py
stonesoup/initiator/simple.py
stonesoup/metricgenerator/manager.py
stonesoup/metricgenerator/metrictables.py
stonesoup/metricgenerator/tests/test_tracktotruthmetrics.py
stonesoup/metricgenerator/tracktotruthmetrics.py
stonesoup/types/state.py

Adds: PA (positional accuracy), VA (velocity accuracy), num_tracks (no. tracks), num_truths (no. ground truth paths),
and single-time: A, S, PA, VA (C already implemented) generators.
Addresses issue #257 'Add additional SIAP Metrics'.

Add Additional SIAPs

---

stonesoup/predictor/kalman.py
stonesoup/predictor/particle.py
stonesoup/types/prediction.py
stonesoup/types/tests/test_prediction.py
stonesoup/types/tests/test_update.py
stonesoup/types/update.py
stonesoup/updater/kalman.py
stonesoup/updater/particle.py

Add handling of various prior types predictors/updater

---

docs/source/stonesoup.types.rst
stonesoup/types/interval.py
stonesoup/types/tests/test_interval.py

Add set-like implementation of closed continuous real intervals

Add closed continuous (real) interval type

---

docs/examples/range_range_rate_binning.py
stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py

Added a Cartesian to elevation, bearing, range and range rate measurement model that bins the range and range rate based on respective resolutions. The model is called RangeRangeRateBinning.

Range velocity binning

---

docs/source/stonesoup.functions.rst
stonesoup/functions/__init__.py
stonesoup/functions/orbital.py
stonesoup/functions/tests/test_functions.py
stonesoup/functions/tests/test_orbital.py
stonesoup/types/angle.py
stonesoup/types/orbitalstate.py

This will enable future functions to be grouped logically, and may also consider breaking up existing functions in future.

Move functions and orbital functions to sub-module

---

docs/source/contributing.rst

In particular, include commands to run tests and build documentation.

Update Contributing documentation

---

docs/tutorials/01_KalmanFilterTutorial.py

Mostly some expansion of the text, as I tried to grok what is happening.

Minor edits for 01 Tutorial

---

stonesoup/dataassociator/tests/test_tracktotrack.py
stonesoup/dataassociator/tracktotrack.py

Create an ID based associator which associates tracks to truths with the same ID.

Add ID based associator

---

docs/source/_templates/breadcrumbs.html

Fix inline with changes on the theme. See: https://github.com/readthedocs/sphinx_rtd_theme/pull/1010

Fix Edit on GitHub links on documentation.

---

docs/examples/ParticleFlow.py
docs/source/conf.py
stonesoup/functions/__init__.py
stonesoup/functions/tests/test_functions.py
stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py
stonesoup/predictor/particle.py
stonesoup/predictor/tests/test_particle.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py
stonesoup/updater/particle.py
stonesoup/updater/tests/test_particle.py

Complete documentation and tests are TODO, as want to first get comments on implementation first.
This was inspired after seeing @DavidFCrouse's paper at FUSION 2019, Particle _Flow Filters: Biases and Bias Avoidance_.

Add Gromov Particle Flow Updater

---

docs/examples/ParticleFlow.py

Conflicted with changes in #384, changing name of time based SIAP metrics

Fix Particle Flow example due to metric name change

---

docs/examples/Metrics.py
docs/source/stonesoup.metricgenerator.plotter.rst
docs/source/stonesoup.metricgenerator.rst
docs/tutorials/10_Simulation_&_Tracking_Components.py
stonesoup/metricgenerator/plotter.py
stonesoup/simulator/simple.py

Change how plotter metric works so it uses the Stone Soup plotting functions from the Plotter class

Fix plotter metric so it uses Stone Soup Plotter class

---

stonesoup/updater/tests/test_particle.py

This would sometimes fail when testing with Gromov Particle Flow

Increase tolerance on particle updater test

---

stonesoup/models/measurement/nonlinear.py
stonesoup/models/measurement/tests/test_models.py

Updated tests to ensure it works for 2D and 3D.

Fix CartesianToBearingRange inverse_function for 3D state space.

---

LICENSE
docs/source/conf.py
stonesoup/__init__.py

Update copyright/license year. 
[ci skip]

Update copyright/license year.

---

stonesoup/plotter.py

Modified plotter to accept track labels as keyword arguments. Adjusted labels to preserve line colour in the legend.

Plotter with track labels

---

stonesoup/base.py
stonesoup/types/tests/test_state.py

- Ensure registered subclasses are in parent subclasses list
- Also updated Property doc string

Ensure registered subclasses are in parent subclasses list

---

stonesoup/dataassociator/base.py
stonesoup/dataassociator/neighbour.py
stonesoup/dataassociator/probability.py
stonesoup/hypothesiser/base.py
stonesoup/hypothesiser/distance.py
stonesoup/hypothesiser/gaussianmixture.py
stonesoup/hypothesiser/probability.py

These updates are primarily to documentation purposes, and also to keep sure `kwargs` was being passed through consistently.

Add DataAssociator and Hypothesiser type hints, and passthrough kwargs

---

stonesoup/plotter.py

Match colours of ellipses, and fix mappings with track uncertainty in Plotter

---

docs/source/stonesoup.dataassociator.rst
setup.py
stonesoup/dataassociator/base.py
stonesoup/dataassociator/neighbour.py
stonesoup/dataassociator/probability.py
stonesoup/dataassociator/tests/conftest.py
stonesoup/dataassociator/tests/test_neighbour.py
stonesoup/dataassociator/tests/test_probability.py
stonesoup/dataassociator/tests/test_tree.py
stonesoup/dataassociator/tree.py

This constructs a kd-tree for detections, wrapping an existing hypothesiser to provide a form of gating. Results in notable performance improvement, and configurable.
TODO:

Add tree data structures for gating

---

README.md

adding orderedSet to dependencies

Updating dependencies in README

---

stonesoup/metricgenerator/plotter.py
stonesoup/metricgenerator/tests/test_plotter.py

Fix plotter metric so it doesn't fail when there are no tracks - closes #456.

Fix plotter metric so it doesn't fail when there are no tracks

---

docs/tutorials/11_GMPHDTutorial.py

Include a tutorial written by Emily Hunter (from DRDC) about how to use the GMPHD filter in Stone Soup in a ground-based situation with near-constant velocity.

Add tutorial on the GMPHD filter in Stone Soup

---

stonesoup/sensor/radar/radar.py

Remove unnecessary additional noise in radar fov check

---

stonesoup/reader/base.py
stonesoup/reader/image.py
stonesoup/reader/tests/test_image.py
stonesoup/reader/video.py

Added SingleImageFileReader class that reads a single image from a file

Added SingleImageFileReader

---

stonesoup/metricgenerator/tests/test_uncertaintymetric.py
stonesoup/metricgenerator/uncertaintymetric.py

This is based from current sum uncertainty metric

Add a mean uncertainty metric

---

stonesoup/runmanager/inputmanager.py
stonesoup/runmanager/runmanagermetrics.py

Added timedelta variable to runmanagerinputs

Added timedela functionality

---

stonesoup/runmanager/inputmanager.py
stonesoup/runmanager/runmanagermetrics.py

Also added some functionality for runmanagermetrics for generating config yaml (not fully functional yet)

added ndarray functionality

---

stonesoup/runmanager/runmanagercore.py

Fixed groundtruth.csv and added failsafes for metrics manager

Fixed groundtruth csv creation and metrics manager fix

---

stonesoup/runmanager/runmanagercore.py

new parameters.json file from FIT project now works with run manager.

Num_runs now works with new parameter file configured in the FIT project

---

stonesoup/types/orbitalstate.py

Orbital methods have moved into an "Orbital" class which OrbitalState and GaussianOrbitalState now inherit from.

Create Orbital class for OrbitalState to inherit from

---

stonesoup/runmanager/runmanagercore.py
stonesoup/runmanager/runmanagermetrics.py
stonesoup/runmanager/temp.py

Cleaned code up and added extra column for ID in groundtruth.csv.

Run manager flake8

---

.circleci/config.yml

Old version of pip has issues with Pillow install

Update pip in CircleCI build

---

stonesoup/resampler/particle.py

Fix typo in documentation for ESSResampler

---

stonesoup/smoother/kalman.py
stonesoup/smoother/tests/test_kalman.py

Includes updates to tests, and a check to ensure that if a multi hypothesis had multiple predictions, that an error would be raised.
Issue raised in https://github.com/dstl/Stone-Soup/discussions/582#discussioncomment-1983887

Enable Kalman Smoother to work with multi-hypothesis states

---

stonesoup/sensor/sensor.py
stonesoup/sensor/tests/test_sensor.py

The intention of this feature is to allow the user to append sensor information to its returned detections.
The SensorSuite type allows the user to define attributes that they would like to be detailed in a sensor's returned detections' metadata.
It can contain multiple sensors, and will yield all their returned detections in one set.

Add sensor suite type

---

docs/source/_templates/breadcrumbs.html

Reference change in: https://github.com/readthedocs/sphinx_rtd_theme/pull/1104

Fix breadcrumbs in documentation

---

docs/tutorials/10_Simulation_&_Tracking_Components.py

Update tutorial 10 plot to use Plotter class.

Update final plot of tutorial 10 to use Plotter class.

---

docs/examples/Moving_Platform_Simulation.py

Resolves issue created by changes in #581

Fix plotting of track state in moving platform example

---

docs/source/_static/css/custom.css

This change was tested with sphinx-gallery 0.10.1 and 0.11, where 0.11 has changed layout requiring the modification.

Fix layout of documentation galleries

---

docs/tutorials/03_UnscentedKalmanFilterTutorial.py

Change legend on polar plots from "Measurements" to "Particles"

Tutorial 3 graph legend fix

---

stonesoup/plotter.py
stonesoup/sensor/radar/radar.py
stonesoup/tests/test_plotter.py

A small change to the Plotter and Plotterly classes.  Previously, there was some contradiction between the documentation and whether or not the primary inputs to the various `plot_` functions could be lists or sets.  This change allows them to be either (ie a Collection), as both are suitable.  
There are also a few miscellaneous grammar fixes to the radar documentation that I've thrown in.

Plotter minor fix

---

stonesoup/plotter.py

Add argument for number of points on ellipse polygon with plotly plotter

---

docs/examples/density_plot_example.py
stonesoup/plotter.py
stonesoup/tests/test_plotter.py

Add 2d density plot to Plotter

---

docs/examples/Creating_Actionable_Sensor.py
stonesoup/sensor/action/__init__.py
stonesoup/sensor/actionable.py

The following changes are introduced:
- Updated ``Create_Actionable_Sensor.py`` example:
- Fixed bullet point formatting
- Minor typo corrections
- Introduced appropriate class, method and attribute references where appropriate
- Defined ``validate_timestamp()`` abstract method in ``Actionable`` class
- Fixed undocumented ``current_property`` property in ``Action`` class

Actionable sensor updates

---

stonesoup/sensor/passive.py
stonesoup/sensor/radar/radar.py
stonesoup/sensor/sensor.py

I've abstracted the `measure` function in the radar & passive sensor. A smaller `is_detectable` function is used, which reuses far less code. It also leaves the door open for the probability of detection to be stochastic

Remove repeated code in sensor

---

stonesoup/measures.py
stonesoup/tests/test_measures.py

Enable pickling of Mahalanobis measure

---

docs/examples/Metrics.py

Simple update of SIAP metric reference in Metrics example.

---

LICENSE
docs/source/conf.py
stonesoup/__init__.py

Copyright year changed from 2022 to 2023

Update copyright year to 2023

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

- Added option to not convert detections when plotting 
- Added option to plot_tracks that all the tracks should have the same colour 
- Added option to specify dimension of plot with an int
- Added documentation

Plotting Improvements

---

docs/source/stonesoup.reader.rst
docs/source/stonesoup.writer.rst
setup.cfg
stonesoup/reader/kafka.py
stonesoup/reader/tests/test_kafka.py
stonesoup/writer/kafka.py
stonesoup/writer/tests/test_kafka.py

This PR contributes the following classes:
- `KafkaDetectionReader`: A detection reader that reads detections from a Kafka broker
- `KafkaGroundTruthReader`: A ground truth reader that reads ground truths from a Kafka broker
- `KafkaWriter`: A simple Kafka writer that writes data to a Kafka topic.

Kafka readers and writers

---

stonesoup/base.py

Fix bug in BaseRepr.whitespace_remove() walrus expression

---

docs/tutorials/01_KalmanFilterTutorial.py

(I'm indebted to Prof Godsill for pointing out the error). For justification see equation 1.4 in 'Beyond the Kalman filter', Ristic et al.

Corrected update equation in Kalman tutorial

---

stonesoup/sensormanager/base.py
stonesoup/sensormanager/optimise.py

Added return_reward, declared when performing chose_actions. Returns the chosen_actions, reward when True

Bool to return reward for BruteForce and Optimise sensor managers

---

docs/examples/Creating_Actionable_Sensor.py
docs/examples/Disjoint_Tracking_Classification.py
docs/examples/Moving_Platform_Simulation.py
docs/examples/Sensor_Platform_Simulation.py
docs/examples/Track_Stitcher_Example.py
docs/examples/density_plot_example.py
stonesoup/platform/base.py
stonesoup/types/association.py

Should improve readability and ensure flake8 tests pass for some examples. Just documentation addition - no coding changes.
Have also changed types/association to fix a typo raised by @A-acuto and put in some full stops while I was there.

Improve example documentation

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

Add initiators for GaussianMixture, ASDGaussian and Ensemble state with accompanying tests

Add GaussianMixtureInitiator, ASDGaussianInitiator and EnsembleInitiator

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

Title gives description. Tests also added. Will link issue this solves.

change unequal timesteps in animated plotter from error to warning

---

stonesoup/movable/action/move_position_action.py
stonesoup/movable/action/tests/test_move_position_action.py
stonesoup/movable/actionable_movable.py

Fix bug in GridActionGenerator where action space limitations were not being applied properly

Fix bug in GridActionGenerator 

---

docs/tutorials/10_Simulation_&_Tracking_Components.py

Small doc changes to tutorial 10. Change sphinx_gallery line so it is not at start of paragraph, and added some words to that section of tutorial.
This fixes issue https://github.com/dstl/Stone-Soup/issues/923

Move sphinx gallery line in tutorial 10

---

docs/examples/Metrics.py

Changes documentation in metrics example. I assume this was originally written in PyCharm where the default character limit is 120.

Make Metrics Example Flake8 Compliant

---

stonesoup/plotter.py
stonesoup/tests/test_plotter.py

Fixes issue [930](https://github.com/dstl/Stone-Soup/issues/930) and adds some simple tests for Plotterly.

Fix error handling for 3d in Plotterly and add tests

---

stonesoup/measures/state.py
stonesoup/measures/tests/test_state.py
stonesoup/predictor/categorical.py
stonesoup/predictor/ensemble.py
stonesoup/predictor/information.py
stonesoup/predictor/kalman.py
stonesoup/predictor/particle.py
stonesoup/smoother/kalman.py
stonesoup/smoother/tests/test_kalman.py
stonesoup/types/prediction.py
stonesoup/updater/dynamicallyiterated.py
stonesoup/updater/iterated.py
stonesoup/updater/kalman.py
stonesoup/updater/tests/test_iterated.py

This PR adds a new updater class: DynamicallyIteratedUpdater (DIEKF) - an implementation of algorithm 2: Dynamically iterated filter, from "Iterated Filters for Nonlinear Transition Models" by Anton Kullberg, Isaac Skog, and Gustaf Hendeby.
Additionally, this PR adds the following as required changes:
1.  Added compatibility to pre-existing Kullback-Leibler divergence measure for GaussianState types.
2. Added prior state as a property of Prediction states. This is required in order for the DIEKF to access and smooth the prior state
3. Updated all relevant Predictor classes to assign the prior state to the output Prediction state.

Dynamically Iterated EKF

---

stonesoup/tracker/simple.py

Correct deleter property documentation

---

docs/ci-requirements.txt
docs/examples/Comparing_EHM_JPDA_example.py
setup.cfg

In this PR I add an example showing qvperformance comparison between hypothesis management between JPDA (brute force) and Efficient Hypothesis Management (EHM) using [PyEHM ](https://github.com/sglvladi/pyehm). 
The example focuses on a Multi-target scenario and compares the computation time perfromances of the three trackers.

Add an example showing performance differences between JPDA and EHM

---

stonesoup/predictor/kalman.py
stonesoup/smoother/kalman.py
stonesoup/updater/tests/test_iterated.py

Fix incorrect transition model being used in Kalman Smoothers

---

docs/examples/Multi_Tracker_Example.py

Variable in now used, set to 1 second timestep so results same as current default.
Resolves #933

Fix unused variable in Comparing Multiple Trackers example

---

stonesoup/functions/__init__.py

Fix calculation of cross-covariance in unscented_transform

---

CITATION.cff

Add repo CITATION file

---

docs/examples/KalmanFilterOOSMExample.py
docs/examples/track_fusion_example.py
setup.cfg
stonesoup/plotter.py

Allow setting of colour to measurements and clutter in Plotterly

---

stonesoup/plotter.py

Includes fix introduce in #990 with clutter plotting, and incorrectly grouping legend items

Fixes to plotting/legends in AnimatedPlotterly

---

docs/source/conf.py
docs/source/doc_extensions.py
setup.cfg

Resolves issues with Sphinx caching (previously warning suppressed), which required update from sphinx-gallery, which has some other breaking changes.

Fixes for Sphinx 7.3 and sphinx-gallery 0.16

---

docs/source/conf.py

Fix issue with nested sections TOC tree in documentation

---

docs/source/_templates/breadcrumbs.html

Fix links to source code from docs "Edit on GitHub" links

---

stonesoup/models/measurement/nonlinear.py
stonesoup/plotter.py

Fix in plotter
In CartesianToElevationBearingRangeRate.inverse_function add velocity of sensor.

Fix CartesianToElevationBearingRangeRate inverse velocity and clutter plotting

---

stonesoup/metricgenerator/ospametric.py
stonesoup/metricgenerator/tests/test_ospametric.py

Use more efficient algorithm in GOSPA assignment

---

docs/demos/OpenSky_Demo.py

This will make it easier to run in local notebook.
Reference #1050

Add download link to OpenSky Demo CSV and full links to icons

---

stonesoup/dataassociator/mfa/_step.py

Infeasible primal problem occurs sometimes due to constraints not being able to be met when sub problem solutions are removed as part of finding primal solution.
This change ignores sub problem solutions when this occurs.

Handle MFA infeasible primal problem

---

.readthedocs.yml

Update to use latest OS, and add now required explicit path to Sphinx configuration path

Update Read The Docs configuration file

---

stonesoup/hypothesiser/mfa.py
stonesoup/hypothesiser/tests/conftest.py
stonesoup/hypothesiser/tests/test_mfa.py
stonesoup/types/mixture.py
stonesoup/types/tests/test_mixture.py

- [Normalise component weights in MFA](https://github.com/dstl/Stone-Soup/commit/d2a096e39d9131620dbfc84d68563f468252f03a)
- [Use from_state in MFA Hypothesiser](https://github.com/dstl/Stone-Soup/commit/f370e758fd6a4c685489dfe04cff5797c421282c)
- [Change MFA and Gaussian mixture to warning not error for multiple timestamps](https://github.com/dstl/Stone-Soup/commit/ecfce07e198d54cf29b21ce63f6fdc7758b2113d)

Multi-Frame Assignment Modifications

---

stonesoup/predictor/asd.py
stonesoup/types/prediction.py
stonesoup/types/state.py
stonesoup/types/tests/test_state.py
stonesoup/types/update.py
stonesoup/updater/asd.py

- [Use from_state in ASD Predictor/Updater](https://github.com/dstl/Stone-Soup/pull/1115/commits/5cbf7ff3516d98f7c961f8895b0081c15d70621a)
- [Add ASDTaggedWeightedGaussianState](https://github.com/dstl/Stone-Soup/pull/1115/commits/7a82882f2d7d63e32d20c988723e614387942e95)

Accumulated State Densities Modifications

---

stonesoup/updater/tests/test_kalman.py

In general set test tolerance to 10¯¹³ for Kalman test

Fix flaky StochasticIntegrationUpdater test

---

stonesoup/updater/tests/test_ensemble.py

Increase number of vectors to make result more stable

Fix flaky ensemble updater tests

---

stonesoup/initiator/simple.py
stonesoup/initiator/tests/test_simple.py

This is like SinglePointInitiator, except the state vector of the measurement is used to replace the prior.
Also update the SingePointInitiator to allow use of updaters other than EKF.

Add SinglePointMeasurementInitiator

---

stonesoup/sensor/sensor.py
stonesoup/sensor/tests/test_sensor.py

This PR adds seeds to `SimpleSensor` based classes similar to setting seeds in `MeasurementModel`

Seed in sensor

---

stonesoup/functions/__init__.py
stonesoup/types/tests/test_angle.py

Fix mod_elevation handling scalar and angle type tests

---

stonesoup/reader/base.py
stonesoup/reader/generic.py
stonesoup/reader/pandas_reader.py
stonesoup/reader/tests/test_generic.py

- Abstracted shared functionality from `_CSVReader` and `_DataFrameReader` into a new `_DictReader` class. Both `_CSVReader` and `_DataFrameReader` now inherit from `_DictReader`.
- Introduced a generic `_DictionaryReader `class capable of reading from a sequence of dictionaries.
- Added a `TrackReader` base class, along with specific implementations for CSV, pandas, and dictionary track readers.

Added Dict Reader. Added Track Reader. Refactored CSV & Pandas DataFrame Reader

---

docs/source/stonesoup.base.rst
stonesoup/base.py
stonesoup/sensormanager/action.py
stonesoup/tests/test_immutable_class.py

For discussion: I wrote these in a separate repo for use in a internal project. 
Are these something of use to the community?

Add ImmutableMixIn and Freezable classes

---

stonesoup/types/array.py
stonesoup/types/tests/test_array.py

Add support to StateVectors `where` and `keepdims` with mean and average
